(async()=>{'use strict';
const B=BABYLON,$=id=>document.getElementById(id),canvas=$('renderCanvas'),status=$('status'),loading=$('loading'),loadText=$('loadText'),loadProgress=$('loadProgress'),errorBox=$('error');
const ORIGIN={lat:59.380767,lon:13.50295};
const BBOX={west:13.4974,south:59.3780,east:13.5086,north:59.3857};
const BASE='https://gi.karlstad.se/arcgis/rest/services/external/KARLSTAD_BaseMap_Sweref99_1330/MapServer';
const TREES='https://gi.karlstad.se/arcgis/rest/services/external/Karlstad_Samlingstjanst/MapServer';
const sceneStats={buildings:0,roads:0,trees:0,land:0,source:'Karlstads kommun'};
const buildingGroups=new Map(),roadMeshes=[],sidewalkMeshes=[],roofMeshes=[],windowMeshes=[],doorMeshes=[];
const metersLon=111320*Math.cos(ORIGIN.lat*Math.PI/180),metersLat=110540;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const local=([lon,lat])=>new B.Vector3((lon-ORIGIN.lon)*metersLon,0,-(lat-ORIGIN.lat)*metersLat);
function setProgress(n,text){loadProgress.style.width=n+'%';if(text)loadText.textContent=text}
function showError(text){errorBox.textContent=text;errorBox.classList.add('show')}
function hash(v){const s=String(v??'');let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)/4294967295}
function area2D(ring){let a=0;for(let i=0,j=ring.length-1;i<ring.length;j=i++)a+=ring[j].x*ring[i].z-ring[i].x*ring[j].z;return Math.abs(a*.5)}
function cleanRing(coords){if(!coords?.length)return[];const out=coords.map(local);if(out.length>1&&B.Vector3.DistanceSquared(out[0],out[out.length-1])<.0001)out.pop();return out}
function mat(name,hex,rough=.82,metal=0){const m=new B.PBRMaterial(name,scene);m.albedoColor=B.Color3.FromHexString(hex);m.roughness=rough;m.metallic=metal;return m}
let engine;
try{
 if(B.WebGPUEngine&&navigator.gpu&&location.protocol==='https:'){const ok=await B.WebGPUEngine.IsSupportedAsync;if(ok){engine=new B.WebGPUEngine(canvas);await engine.initAsync();engine.__backend='WebGPU'}}
}catch(e){console.warn('WebGPU fallback',e)}
if(!engine){engine=new B.Engine(canvas,true,{antialias:true,stencil:true,adaptToDeviceRatio:true});engine.__backend='WebGL2'}
const scene=new B.Scene(engine);scene.clearColor=new B.Color4(.55,.68,.72,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.00115;scene.fogColor=new B.Color3(.55,.68,.72);scene.gravity=new B.Vector3(0,-.42,0);scene.collisionsEnabled=true;
scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.toneMappingType=B.ImageProcessingConfiguration.TONEMAPPING_ACES;scene.imageProcessingConfiguration.exposure=1.05;scene.imageProcessingConfiguration.contrast=1.12;
const camera=new B.UniversalCamera('player',new B.Vector3(0,1.8,0),scene);camera.minZ=.05;camera.maxZ=1300;camera.fov=1.08;camera.inertia=.72;camera.angularSensibility=3800;camera.speed=.75;camera.checkCollisions=false;camera.applyGravity=false;camera.ellipsoid=new B.Vector3(.34,.86,.34);camera.keysUp.push(87);camera.keysDown.push(83);camera.keysLeft.push(65);camera.keysRight.push(68);camera.attachControl(canvas,true);camera.setTarget(new B.Vector3(0,1.8,-40));
const hemi=new B.HemisphericLight('sky',new B.Vector3(0,1,0),scene);hemi.intensity=.86;hemi.diffuse=B.Color3.FromHexString('#c8dce2');hemi.groundColor=B.Color3.FromHexString('#45523d');
const sun=new B.DirectionalLight('sun',new B.Vector3(.55,-.75,.36),scene);sun.position=new B.Vector3(-220,320,-250);sun.diffuse=B.Color3.FromHexString('#ffe2b8');sun.intensity=2.1;
const shadows=new B.ShadowGenerator(matchMedia('(pointer:coarse)').matches?1024:2048,sun);shadows.usePercentageCloserFiltering=true;shadows.filteringQuality=B.ShadowGenerator.QUALITY_LOW;shadows.bias=.0015;shadows.normalBias=.03;shadows.darkness=.32;
try{const pipe=new B.DefaultRenderingPipeline('real-city-pipe',true,scene,[camera]);pipe.fxaaEnabled=true;pipe.bloomEnabled=true;pipe.bloomThreshold=.9;pipe.bloomWeight=.09;pipe.bloomKernel=32;pipe.samples=1}catch(e){}
const M={ground:mat('ground','#89907a',.94),asphalt:mat('asphalt','#4d5758',.76),paving:mat('square granite','#9b9a8e',.62),sidewalk:mat('sidewalk','#a7a79a',.86),water:mat('river','#4e8491',.18,.22),roof:mat('roof','#38484a',.58,.35),tree:mat('leaves','#537742',.94),trunk:mat('trunk','#5f4938',.98),glass:mat('window glass','#34505c',.22,.35),door:mat('doors','#44382f',.82),park:mat('park grass','#698454',.96)};
const buildingMats=[mat('ochre plaster','#b89a72',.82),mat('brick','#7a5548',.9),mat('pale stone','#c7c0aa',.84),mat('warm grey','#8c8c80',.88),mat('painted facade','#a8b0a4',.86),mat('civic stone','#afa892',.78)];
let windowBudget=1500,doorBudget=260;
function centroid2D(ring){let x=0,z=0;for(const p of ring){x+=p.x;z+=p.z}const n=ring.length||1;return new B.Vector3(x/n,0,z/n)}
function longestAxis(ring){let best={len:0,u:new B.Vector3(1,0,0)};for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);if(len>best.len)best={len,u:new B.Vector3(dx/len,0,dz/len)}}const v=new B.Vector3(-best.u.z,0,best.u.x),center=centroid2D(ring);let minU=Infinity,maxU=-Infinity,minV=Infinity,maxV=-Infinity;for(const p of ring){const d=p.subtract(center),pu=B.Vector3.Dot(d,best.u),pv=B.Vector3.Dot(d,v);minU=Math.min(minU,pu);maxU=Math.max(maxU,pu);minV=Math.min(minV,pv);maxV=Math.max(maxV,pv)}return{u:best.u,v,center,hu:(maxU-minU)/2,hv:(maxV-minV)/2}}
function addFacadeDetails(ring,h,props,index){if(windowBudget<=0)return;const floors=clamp(Math.round((h-1)/3.05),1,6),center=centroid2D(ring);let longest={len:0,a:null,b:null,n:null};for(let e=0;e<ring.length;e++){const a=ring[e],b=ring[(e+1)%ring.length],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);if(len<4)continue;let nx=-dz/len,nz=dx/len,mid=new B.Vector3((a.x+b.x)/2,0,(a.z+b.z)/2);if((center.x-mid.x)*nx+(center.z-mid.z)*nz>0){nx=-nx;nz=-nz}if(len>longest.len)longest={len,a,b,n:{x:nx,z:nz}};const count=Math.max(1,Math.min(5,Math.floor((len-1.2)/2.7)));for(let floor=0;floor<floors&&windowBudget>0;floor++){const y=1.35+floor*3.05;if(y+1>h)break;for(let w=0;w<count&&windowBudget>0;w++){const t=(w+1)/(count+1),x=a.x+dx*t+nx*.055,z=a.z+dz*t+nz*.055,win=B.MeshBuilder.CreateBox('window',{width:.86,height:1.18,depth:.055},scene);win.position.set(x,y,z);win.rotation.y=Math.atan2(nx,nz);win.material=M.glass;win.isPickable=false;windowMeshes.push(win);windowBudget--;}}}
 if(doorBudget>0&&longest.a){const {a,b,n}=longest,door=B.MeshBuilder.CreateBox('door',{width:1.1,height:2.15,depth:.07},scene);door.position.set((a.x+b.x)/2+n.x*.07,1.075,(a.z+b.z)/2+n.z*.07);door.rotation.y=Math.atan2(n.x,n.z);door.material=M.door;door.isPickable=false;doorMeshes.push(door);doorBudget--;}}
function customRoof(name,ring,h,kind){const o=longestAxis(ring),hu=o.hu,hv=o.hv;if(hu<2||hv<2)return null;const rise=clamp(Math.min(3.8,hv*.55),1.15,4.2),rf=kind==='hipped'?.58:1,u=o.u,v=o.v,c=o.center;function P(du,dv,y){return[c.x+u.x*du+v.x*dv,y,c.z+u.z*du+v.z*dv]}const A=P(-hu,-hv,h),B1=P(hu,-hv,h),C1=P(hu,hv,h),D=P(-hu,hv,h),E=P(-hu*rf,0,h+rise),F=P(hu*rf,0,h+rise),pos=[],idx=[];function face(points){const base=pos.length/3;for(const p of points)pos.push(...p);if(points.length===3)idx.push(base,base+1,base+2);else idx.push(base,base+1,base+2,base,base+2,base+3)}face([A,B1,F,E]);face([D,E,F,C1]);face([A,E,D]);face([B1,C1,F]);const vd=new B.VertexData();vd.positions=pos;vd.indices=idx;vd.normals=[];B.VertexData.ComputeNormals(pos,idx,vd.normals);const m=new B.Mesh(name,scene);vd.applyToMesh(m);m.material=M.roof;m.receiveShadows=true;m.isPickable=false;roofMeshes.push(m);return m}
function addRoof(ring,holes,h,props,index){const t=String(props['roof:shape']||props.roof_shape||'').toLowerCase(),a=area2D(ring),r=hash((props.FID||props.OBJECTID||index)+'roof');let kind=t.includes('hip')?'hipped':t.includes('gable')?'gabled':t.includes('flat')?'flat':(a>1200?'flat':r<.48?'gabled':r<.76?'hipped':'flat');if(kind==='flat'){try{const cap=B.MeshBuilder.CreatePolygon('roof cap '+index,{shape:ring,holes,sideOrientation:B.Mesh.DOUBLESIDE},scene,earcut);cap.position.y=h+.04;cap.material=M.roof;cap.receiveShadows=true;cap.isPickable=false;roofMeshes.push(cap)}catch(e){}}else customRoof('roof '+kind+' '+index,ring,h,kind)}

const ground=B.MeshBuilder.CreateGround('ground',{width:1300,height:1300,subdivisions:1},scene);ground.material=M.ground;ground.receiveShadows=true;ground.checkCollisions=true;ground.position.y=-.03;
function arcgisUrl(root,layer,outFields='*'){
 const u=new URL(`${root}/${layer}/query`);u.search=new URLSearchParams({where:'1=1',geometry:`${BBOX.west},${BBOX.south},${BBOX.east},${BBOX.north}`,geometryType:'esriGeometryEnvelope',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields,returnGeometry:'true',outSR:'4326',f:'geojson'}).toString();return u.toString();
}
async function getJson(url,ms=18000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),ms);try{const r=await fetch(url,{signal:ctrl.signal,mode:'cors'});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function loadMunicipal(){
 const urls={buildings:arcgisUrl(BASE,23,'FID,DETALJTYP,OBJEKTTYP,BALSTATUS'),roads:arcgisUrl(BASE,29,'FID,KLASS,RLID'),land:arcgisUrl(BASE,36,'FID,DETALJTYP,OBJEKTTYP'),trees:arcgisUrl(TREES,190,'OBJECTID,objid,tradslag,tradtyp,dbh,storlek')};
 const pairs=await Promise.allSettled(Object.entries(urls).map(async([k,u])=>[k,await getJson(u,6000)]));const data={};for(const p of pairs)if(p.status==='fulfilled')data[p.value[0]]=p.value[1];
 if(!data.buildings?.features?.length)throw Error('Kommunens byggnadslager kunde inte läsas');return data;
}
async function loadOsmFallback(){
 const q=`[out:json][timeout:18];(way[building](${BBOX.south},${BBOX.west},${BBOX.north},${BBOX.east});way[highway](${BBOX.south},${BBOX.west},${BBOX.north},${BBOX.east}););out tags geom;`;
 const url='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q),j=await getJson(url,20000),buildings=[],roads=[];
 for(const e of j.elements||[]){const props={...e.tags,FID:e.id,OBJECTID:e.id,OBJEKTTYP:e.tags?.building||'',BALSTATUS:'Gällande'};if(e.type!=='way'||!e.geometry?.length)continue;const coords=e.geometry.map(p=>[p.lon,p.lat]);if(e.tags?.building){if(coords.length>2)buildings.push({type:'Feature',properties:props,geometry:{type:'Polygon',coordinates:[coords]}})}else if(e.tags?.highway)roads.push({type:'Feature',properties:{...props,KLASS:e.tags.highway},geometry:{type:'LineString',coordinates:coords}})}
 sceneStats.source='OpenStreetMap fallback';return{buildings:{features:buildings},roads:{features:roads},land:{features:[]},trees:{features:[]}};
}
async function loadOsmTrees(){
 const q=`[out:json][timeout:12];node[natural=tree](${BBOX.south},${BBOX.west},${BBOX.north},${BBOX.east});out tags;`;
 const url='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q),j=await getJson(url,14000),trees=[];
 for(const e of j.elements||[]){if(e.type!=='node')continue;trees.push({type:'Feature',properties:{OBJECTID:e.id,tradslag:e.tags?.species||e.tags?.genus||'',dbh:e.tags?.diameter_crown||40},geometry:{type:'Point',coordinates:[e.lon,e.lat]}})}
 return trees;
}
function estimateHeight(props,ring){const tagged=parseFloat(props.height);if(Number.isFinite(tagged))return clamp(tagged,3,35);const levels=parseFloat(props['building:levels']);if(Number.isFinite(levels))return clamp(levels*3.05+1,4,32);const t=String(props.OBJEKTTYP||props.building||'').toLowerCase(),a=area2D(ring),r=hash(props.FID||props.OBJECTID||a);let h=t.includes('samhäll')||t.includes('civic')?12:t.includes('industri')?8:t.includes('komplement')?4.2:t.includes('kyrk')||t.includes('samfund')?14:t.includes('verksam')?10:9;if(a>900)h+=3;if(a>2200)h+=2;return clamp(h+(r-.5)*5,4,22)}
function buildingMaterial(props){const t=String(props.OBJEKTTYP||props.building||'').toLowerCase();if(t.includes('samhäll')||t.includes('civic')||t.includes('samfund'))return buildingMats[5];if(t.includes('industri'))return buildingMats[3];if(t.includes('verksam'))return buildingMats[2];const i=Math.floor(hash(props.FID||props.OBJECTID)*5);return buildingMats[i]}
function polygonParts(feature){const g=feature.geometry;if(!g)return[];if(g.type==='Polygon')return[g.coordinates];if(g.type==='MultiPolygon')return g.coordinates;return[]}
function createBuilding(feature,index){let made=0;for(const poly of polygonParts(feature)){const outer=cleanRing(poly[0]);if(outer.length<3||area2D(outer)<7)continue;const holes=(poly.slice(1)||[]).map(cleanRing).filter(r=>r.length>2);const h=estimateHeight(feature.properties||{},outer);try{const mesh=B.MeshBuilder.ExtrudePolygon(`building ${feature.properties?.FID||index}`,{shape:outer,holes,depth:h,sideOrientation:B.Mesh.DOUBLESIDE},scene,earcut);mesh.position.y=h;mesh.material=buildingMaterial(feature.properties||{});mesh.checkCollisions=true;mesh.receiveShadows=true;mesh.isPickable=false;mesh.metadata={source:'Karlstads kommun / generated height',height:h,properties:feature.properties};if(!buildingGroups.has(mesh.material))buildingGroups.set(mesh.material,[]);buildingGroups.get(mesh.material).push(mesh);made++}catch(e){console.warn('building skipped',e)}}return made}
function lineParts(g){if(!g)return[];if(g.type==='LineString')return[g.coordinates];if(g.type==='MultiLineString')return g.coordinates;return[]}
function roadWidth(props){const c=String(props.KLASS||props.highway||'').toLowerCase();if(['0','1','2','primary','secondary','trunk'].includes(c))return 7;if(['3','4','5','tertiary','residential'].includes(c))return 5;return 3.2}
function createRoad(feature,index){let made=0;for(const coords of lineParts(feature.geometry)){const pts=coords.map(local);if(pts.length<2)continue;const half=roadWidth(feature.properties||{})/2,left=[],right=[];for(let i=0;i<pts.length;i++){const p=pts[i],a=pts[Math.max(0,i-1)],b=pts[Math.min(pts.length-1,i+1)],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz)||1,nx=-dz/len,nz=dx/len;left.push(new B.Vector3(p.x+nx*half,.02,p.z+nz*half));right.push(new B.Vector3(p.x-nx*half,.02,p.z-nz*half))}try{const m=B.MeshBuilder.CreateRibbon(`road ${index}`,{pathArray:[left,right],closeArray:false,closePath:false,sideOrientation:B.Mesh.DOUBLESIDE,updatable:false},scene);m.material=M.asphalt;m.receiveShadows=true;m.isPickable=false;roadMeshes.push(m);made++}catch(e){}}return made}
function createLand(feature,index){const type=String(feature.properties?.OBJEKTTYP||feature.properties?.DETALJTYP||'').toLowerCase();if(!(type.includes('vatten')||type.includes('sjö')||type.includes('vattendrag')||type.includes('torg')))return 0;let made=0;for(const poly of polygonParts(feature)){const outer=cleanRing(poly[0]);if(outer.length<3)continue;const holes=(poly.slice(1)||[]).map(cleanRing).filter(r=>r.length>2);try{const m=B.MeshBuilder.CreatePolygon(`land ${index}`,{shape:outer,holes,sideOrientation:B.Mesh.DOUBLESIDE},scene,earcut);m.position.y=type.includes('torg')?.025:.005;m.material=type.includes('torg')?M.paving:M.water;m.receiveShadows=!type.includes('vatten');m.isPickable=false;made++}catch(e){}}return made}
const trunkSource=B.MeshBuilder.CreateCylinder('tree trunk source',{height:3,diameterTop:.26,diameterBottom:.38,tessellation:7},scene);trunkSource.material=M.trunk;trunkSource.position.y=-100;
const crownSource=B.MeshBuilder.CreateIcoSphere('tree crown source',{radius:1.7,subdivisions:1},scene);crownSource.material=M.tree;crownSource.position.y=-100;
function createTree(feature,index){if(feature.geometry?.type!=='Point')return 0;const p=local(feature.geometry.coordinates),dbh=Number(feature.properties?.dbh)||40,scale=clamp(.75+dbh/110,.75,1.65);const t=trunkSource.createInstance('trunk '+index);t.position.set(p.x,1.5*scale,p.z);t.scaling.set(scale,scale,scale);const c=crownSource.createInstance('crown '+index);c.position.set(p.x,4.2*scale,p.z);c.scaling.set(scale,scale*.9,scale);return 1}
function label(text,lon,lat,color='#ffcb70'){const p=local([lon,lat]),root=new B.TransformNode(text,scene);root.position.set(p.x,0,p.z);const ring=B.MeshBuilder.CreateTorus(text+' ring',{diameter:2.6,thickness:.05,tessellation:40},scene);ring.parent=root;ring.position.y=.08;const em=new B.StandardMaterial(text+' glow',scene);em.emissiveColor=B.Color3.FromHexString(color);em.disableLighting=true;ring.material=em;const tex=new B.DynamicTexture(text+' tex',{width:512,height:96},scene,true),ctx=tex.getContext();ctx.clearRect(0,0,512,96);ctx.fillStyle='#071218dd';ctx.fillRect(0,0,512,96);ctx.fillStyle='#f5f0df';ctx.font='700 28px system-ui';ctx.textAlign='center';ctx.fillText(text,256,60);tex.update();const lm=new B.StandardMaterial(text+' mat',scene);lm.diffuseTexture=tex;lm.opacityTexture=tex;lm.emissiveColor=new B.Color3(.55,.55,.55);lm.backFaceCulling=false;const pl=B.MeshBuilder.CreatePlane(text+' label',{width:7.2,height:1.35},scene);pl.parent=root;pl.position.y=4.4;pl.material=lm;pl.billboardMode=B.Mesh.BILLBOARDMODE_ALL;return root}
label('STORA TORGET',13.50295,59.380767);label('SANDGRUND',13.502961,59.384639,'#9de0c9');label('VÄRMLANDS MUSEUM',13.50124,59.38492,'#9de0c9');
const localPilot=location.hostname==='localhost'||location.hostname==='127.0.0.1';
let data;
if(localPilot){
 setProgress(12,'Laddar lokal Real City-pilot via OSM…');
 try{data=await loadOsmFallback()}catch(e){console.error(e);showError('OSM-reserven svarade inte. Ladda om sidan om en stund.');data={buildings:{features:[]},roads:{features:[]},land:{features:[]},trees:{features:[]}}}
}else{
 try{setProgress(12,'Hämtar Karlstads byggnadsytor…');data=await loadMunicipal()}catch(e){console.warn(e);setProgress(18,'Kommunens live-endpoint svarade inte. Försöker OSM-reserv…');try{data=await loadOsmFallback();showError('Kommunens ArcGIS-endpoint kunde inte nås från webbläsaren. Piloten kör därför OSM som reservkälla i denna session.')}catch(e2){console.error(e2);showError('Varken Karlstads öppna endpoint eller reservkällan kunde läsas. Kontrollera internetanslutningen och ladda om.');data={buildings:{features:[]},roads:{features:[]},land:{features:[]},trees:{features:[]}}}}
}
setProgress(38,'Bygger verkliga byggnadsytor…');await new Promise(r=>requestAnimationFrame(r));
for(const [i,f] of (data.buildings?.features||[]).entries()){if(String(f.properties?.BALSTATUS||'Gällande').toLowerCase().includes('planerad'))continue;sceneStats.buildings+=createBuilding(f,i);if(i%80===0)await new Promise(r=>requestAnimationFrame(r))}
setProgress(58,'Optimerar byggnader…');for(const [material,meshes] of buildingGroups){if(!meshes.length)continue;const merged=B.Mesh.MergeMeshes(meshes,true,true,undefined,false,false);if(merged){merged.name='real buildings / '+material.name;merged.material=material;merged.checkCollisions=true;merged.receiveShadows=true;merged.isPickable=false;merged.freezeWorldMatrix();shadows.addShadowCaster(merged)}}
setProgress(66,'Lägger ut gatunät och mark…');for(const [i,f] of (data.roads?.features||[]).entries())sceneStats.roads+=createRoad(f,i);if(roadMeshes.length>1){const mergedRoad=B.Mesh.MergeMeshes(roadMeshes,true,true,undefined,false,false);if(mergedRoad){mergedRoad.name='real roads';mergedRoad.material=M.asphalt;mergedRoad.receiveShadows=true;mergedRoad.freezeWorldMatrix()}}for(const [i,f] of (data.land?.features||[]).entries())sceneStats.land+=createLand(f,i);
setProgress(78,'Planterar tillgängliga träd…');for(const [i,f] of (data.trees?.features||[]).slice(0,450).entries())sceneStats.trees+=createTree(f,i);
setProgress(91,'Optimerar scenen för mobilen…');scene.blockMaterialDirtyMechanism=true;for(const material of scene.materials)material.freeze?.();
setProgress(100,'Karlstad klart');status.textContent=`${engine.__backend} · ${sceneStats.source==='OpenStreetMap fallback'?'OSM · ':''}${sceneStats.buildings} HUS · ${sceneStats.roads} VÄGAR · ${sceneStats.trees} TRÄD`;
setTimeout(()=>loading.classList.add('hidden'),350);
if(sceneStats.trees===0){
 loadOsmTrees().then(features=>{for(const [i,f] of features.slice(0,450).entries())sceneStats.trees+=createTree(f,i);status.textContent=`${engine.__backend} · ${sceneStats.source==='OpenStreetMap fallback'?'OSM · ':''}${sceneStats.buildings} HUS · ${sceneStats.roads} VÄGAR · ${sceneStats.trees} TRÄD`;}).catch(e=>console.warn('Tree layer deferred:',e));
}
const spawn=new B.Vector3(0,1.8,0);camera.position.copyFrom(spawn);camera.setTarget(new B.Vector3(0,1.8,-35));$('reset').addEventListener('click',()=>{camera.position.copyFrom(spawn);camera.rotation.set(0,Math.PI,0);camera.setTarget(new B.Vector3(0,1.8,-35))});$('collision').addEventListener('click',()=>{camera.checkCollisions=!camera.checkCollisions;camera.applyGravity=camera.checkCollisions;$('collision').textContent=camera.checkCollisions?'COLL ON':'COLL OFF';});
let joy={active:false,id:null,x:0,y:0},joyEl=$('joy'),knob=$('knob');function joyPos(x,y){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=x-cx,dy=y-cy,max=33,len=Math.hypot(dx,dy)||1;if(len>max){dx*=max/len;dy*=max/len}joy.x=dx/max;joy.y=dy/max;knob.style.left=38+dx+'px';knob.style.top=38+dy+'px'}joyEl.addEventListener('pointerdown',e=>{joy.active=true;joy.id=e.pointerId;joyEl.setPointerCapture(e.pointerId);joyPos(e.clientX,e.clientY)});joyEl.addEventListener('pointermove',e=>{if(joy.active&&e.pointerId===joy.id)joyPos(e.clientX,e.clientY)});function joyEnd(e){if(e.pointerId===joy.id){joy.active=false;joy.x=joy.y=0;knob.style.left=knob.style.top='38px'}}joyEl.addEventListener('pointerup',joyEnd);joyEl.addEventListener('pointercancel',joyEnd);
let look={active:false,id:null,x:0,y:0},lookEl=$('look');lookEl.addEventListener('pointerdown',e=>{look.active=true;look.id=e.pointerId;look.x=e.clientX;look.y=e.clientY;lookEl.setPointerCapture(e.pointerId)});lookEl.addEventListener('pointermove',e=>{if(!look.active||e.pointerId!==look.id)return;const dx=e.clientX-look.x,dy=e.clientY-look.y;look.x=e.clientX;look.y=e.clientY;camera.rotation.y+=dx*.0037;camera.rotation.x=clamp(camera.rotation.x+dy*.0028,-1.35,1.35)});lookEl.addEventListener('pointerup',e=>{if(e.pointerId===look.id)look.active=false});lookEl.addEventListener('pointercancel',e=>{if(e.pointerId===look.id)look.active=false});
scene.onBeforeRenderObservable.add(()=>{if(!joy.active)return;const dt=engine.getDeltaTime()/16.67,forward=-joy.y,right=joy.x,y=camera.rotation.y;const dx=(Math.sin(y)*forward+Math.cos(y)*right)*.42*dt,dz=(Math.cos(y)*forward-Math.sin(y)*right)*.42*dt;camera.cameraDirection.addInPlace(new B.Vector3(dx,0,dz))});
engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());
})();
