/* Original generative score and environmental sound design; no third-party recordings. */
window.KarlstadAudio=class {
 constructor(){this.ctx=null;this.on=false;this.next=0;this.beat=0;this.foot=0;this.ambience=[]}
 start(){try{if(!this.ctx){const A=window.AudioContext||window.webkitAudioContext;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.34;this.master.connect(this.ctx.destination);this.music=this.ctx.createGain();this.music.gain.value=.34;this.music.connect(this.master);this.noise=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate);let d=this.noise.getChannelData(0),last=0;for(let i=0;i<d.length;i++){last=(last+Math.random()*.12-.06)/1.012;d[i]=last*2.8}const src=this.ctx.createBufferSource();src.buffer=this.noise;src.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=420;const gain=this.ctx.createGain();gain.gain.value=.08;src.connect(filter).connect(gain).connect(this.master);src.start();this.ambience.push(src)}this.ctx.resume();this.on=true;this.master.gain.setTargetAtTime(.34,this.ctx.currentTime,.18)}catch(e){this.on=false}return this.on}
 toggle(){if(!this.ctx||!this.on)return this.start();this.on=false;this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.12);return false}
 tone(freq,duration=.3,volume=.09,type='sine',delay=0,end=0,dest=this.master){if(!this.ctx||!this.on)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(22,end),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(dest);o.start(t);o.stop(t+duration+.03)}
 hiss(duration,volume,cutoff=600){if(!this.ctx||!this.on)return;const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain(),t=this.ctx.currentTime;src.buffer=this.noise;f.type='lowpass';f.frequency.value=cutoff;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(f).connect(g).connect(this.master);src.start(t);src.stop(t+duration)}
 fx(type){if(type==='scan'){this.tone(260,.45,.10,'sine',0,1100);this.tone(1740,.22,.025,'sine',.25);this.hiss(.36,.12,2400)}if(type==='win'){[293.66,369.99,440,587.33].forEach((f,i)=>this.tone(f,.9,.1,'triangle',i*.13));this.tone(73.42,1.3,.14,'sine')}if(type==='step'){this.hiss(.11,.17,650);this.tone(84,.09,.022,'sine',0,38)}if(type==='click')this.tone(620,.055,.036);if(type==='miss')this.tone(180,.2,.05,'triangle',0,115);if(type==='bus'){this.tone(44,3,.07,'sawtooth',0,75);this.hiss(1,.06,130)}if(type==='bird'){this.tone(1600,.13,.015,'sine',0,2300);this.tone(2100,.16,.012,'sine',.17,1750)}}
 tick(mode,dt,moving=false,sprint=false){if(!this.ctx||!this.on||mode==='paused')return;const t=this.ctx.currentTime;if(t>this.next){this.next=t+.46;const n=this.beat++%32,notes=[293.66,440,587.33,369.99,329.63,493.88,659.25,440,261.63,392,523.25,329.63,293.66,440,587.33,220];if(n%2===0)this.tone(notes[n/2],1.9,.09,'triangle',0,0,this.music);if(n%8===0){this.tone(n<16?73.42:65.4,3.8,.16,'sine',0,0,this.music);this.tone(n<16?146.83:130.81,3.5,.035,'triangle',0,0,this.music)}if(mode==='ride'&&n%4===0)this.tone(95,.28,.08,'sine',0,35,this.music);if(n===22)this.fx('bird')}if(moving&&mode==='play'){this.foot+=dt;if(this.foot>(sprint?.25:.39)){this.foot=0;this.fx('step')}}else this.foot=0}
 suspend(){if(this.ctx)this.ctx.suspend()}
 resume(){if(this.ctx&&this.on)this.ctx.resume()}
};
