/* Karlstad City Quest — cinematic pilot. Gameplay, navigation and accessible UI. */
(()=>{'use strict';
const $=id=>document.getElementById(id), STORAGE='karlstad-cinematic-v1';
const MISSIONS=[
 {id:'library',title:'Biblioteket har flyttat',short:'BIBLIOTEKET',kind:'STADSSERVICE',icon:'▤',place:'Arkaden · Östra Torggatan 9',lat:59.37995,lng:13.504023,x:11,z:5,node:3,xp:150,hint:'Hitta entrén till Arkaden. Scanna signalen vid biblioteket.',story:'En återlämnad bok har hamnat vid den gamla byggnaden. Följ stadens gyllene spår och hitta bibliotekets nya hem.',fact:'Stadsbiblioteket och Kontaktcenter har öppnat sina tillfälliga lokaler i Arkaden, på Östra Torggatan 9.',question:'Vilken adress ska du hjälpa nästa besökare att hitta?',options:['Östra Torggatan 9','Västra Torggatan 31','Stora torget 1'],answer:0,success:'På lånekortets baksida framträder en sol: ”Sök ljuset där konsten möter älven.”',source:'Karlstads kommun',url:'https://karlstad.se/nyheter/uppleva-och-gora/uppleva-och-gora/2026-09-02-stadsbiblioteket-och-kontaktcenter-har-oppnat-i-sina-tillfalliga-lokaler'},
 {id:'sandgrund',title:'Spår av ljus',short:'SANDGRUND',kind:'KULTUR · SCANNERUPPDRAG',icon:'✧',place:'Sandgrund Lars Lerin',lat:59.384639,lng:13.502961,x:25,z:96,node:6,xp:200,hint:'Nå Sandgrund. Där väntar tre fragment av stadens ljus.',story:'Vid älven har tre ljusfragment fastnat i skulpturträdgården. Använd scannern nära varje signal och sätt ihop ledtråden.',fact:'Sandgrund är Lars Lerins permanenta konsthall. Tillfälliga gästutställningar ger nya anledningar att komma tillbaka.',success:'Fragmenten bildar ett ord: MUSEET. Stadens berättelser väntar på andra sidan kulturplatsen.',source:'Sandgrund Lars Lerin',url:'https://sandgrund.org/sandgrund/'},
 {id:'museum',title:'Stadens berättelser',short:'MUSEET',kind:'UPPTÄCK HISTORIEN',icon:'◈',place:'Värmlands Museum · Sandgrundsudden',lat:59.38492,lng:13.50124,x:-24,z:98,node:7,xp:150,hint:'Följ spåret till museets entré och tyd nästa ledtråd.',story:'Scannern hittar ett gammalt kartfragment vid museets entré. Ett platsnamn saknas. Fyll i det för att öppna resans nästa kapitel.',fact:'Värmlands Museum ligger på Sandgrundsudden, nära Sandgrund Lars Lerin och Klarälven.',question:'Vilken udde ligger Värmlands Museum på?',options:['Sandgrundsudden','Lamberget','Hammarö'],answer:0,success:'På kartans nästa sida finns en resa markerad: ”Sök den gröna oasen söder om centrum.”',source:'Värmlands Museum',url:'https://varmlandsmuseum.se/besok-oss/hitta-hit/'},
 {id:'bus',title:'Ta staden vidare',short:'BUSSÄVENTYRET',kind:'RESA SMART',icon:'▰',place:'Centrum → Mariebergsskogen',lat:59.380750,lng:13.503111,x:-8,z:-14,node:17,xp:150,hint:'Återvänd till busshållplatsen. En grön hemlighet väntar.',story:'Du har hittat kulturspåret. Nu väntar en ny del av Karlstad. Kliv ombord i spelet och följ resan över älven.',fact:'Resan är en spelad sekvens. Verkliga hållplatser, avgångar och biljetter kontrollerar du hos Värmlandstrafik.',success:'Du är framme vid Mariebergsskogen. Sista signalen kommer från naturum.',source:'Värmlandstrafik',url:'https://www.varmlandstrafik.se/'},
 {id:'park',title:'Den gröna hemligheten',short:'NATURUM',kind:'HIDDEN GEM',icon:'✳',place:'naturum Värmland · Mariebergsskogen',lat:59.369119,lng:13.487801,x:-124,z:-95,node:13,xp:200,hint:'Följ stigen genom parken och hitta naturum Värmland.',story:'Bland träden blir stadens brus till fågelsång. Den sista signalen leder till en plats som öppnar dörren till värmländsk natur.',fact:'I Mariebergsskogen finns naturum Värmland. Där kan du upptäcka mer om naturen i Värmland. Kontrollera öppettider före ett riktigt besök.',question:'Vad heter platsen som berättar om värmländsk natur?',options:['naturum Värmland','Stadshuset','Sandgrund Lars Lerin'],answer:0,success:'Du har följt berättelsen från biblioteket till kultur och natur. Stadens solsigill är ditt.',source:'Karlstads kommun · naturum',url:'https://karlstad.se/mariebergsskogen/upptack-mariebergsskogen/naturum-varmland'}
];
const nodes=[[0,-24],[0,-14],[0,5],[11,5],[0,53],[0,88],[25,96],[-24,98],[0,-48],[-49,-48],[-104,-48],[-124,-48],[-124,-78],[-124,-95],[15,87],[32,90],[27,79],[-8,-7]];
const edges=[[0,1],[1,2],[2,3],[2,4],[4,5],[5,6],[5,7],[0,8],[8,9],[9,10],[10,11],[11,12],[12,13],[5,14],[14,6],[6,15],[15,16],[14,16],[2,17]];
const audio=new KarlstadAudio(), canvas=$('renderCanvas'), ui=$('ui');
let world,engine,softwareRenderer=null,mode='loading',time=0,introTime=0,last=0,yaw=0,pitch=0,bob=0,scanRecoil=0,toastUntil=0,guide=[],guideIndex=0,lookTime=-10,quality=matchMedia('(pointer:coarse), (max-width:700px)').matches?'mobile':'high',qualityAuto=false,frameSamples=0,slowTime=0,rideTime=0,rideStart=0,modalType='',lastFocus=null,sceneMap=null,mapMarkers=[],mapLoading=false,jumping=0,jumpVelocity=0;
const keys=new Set(),input={x:0,y:0,sprint:false},player={x:0,z:-24};let save=readSave();let scanning=false,seen=new Set(),hudClock=0,screenClock=0;
function readSave(){try{const v=JSON.parse(localStorage.getItem(STORAGE));if(!v||!Number.isInteger(v.done)||v.done<0||v.done>5)throw 0;return {done:v.done,fragments:Array.isArray(v.fragments)?[...new Set(v.fragments.filter(i=>Number.isInteger(i)&&i>=0&&i<3))]:[]}}catch{return {done:0,fragments:[]}}}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(save))}catch{}}
const active=()=>Math.min(save.done,4),current=()=>MISSIONS[active()],score=()=>MISSIONS.slice(0,save.done).reduce((a,m)=>a+m.xp,0),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
function deltaAngle(a,b){return Math.atan2(Math.sin(b-a),Math.cos(b-a))}
function setMode(m){mode=m;ui.dataset.mode=m;keys.clear();input.x=input.y=0;input.sprint=false;$('joystickKnob').style.transform='';if(world)world.scanner.setEnabled(m==='play');if(m!=='play'&&document.pointerLockElement)document.exitPointerLock?.()}
function toast(title,text,seconds=4){$('toastTitle').textContent=title;$('toastText').textContent=text;$('toast').classList.add('visible');toastUntil=time+seconds}
function target(){if(scanning){const i=[0,1,2].find(n=>!save.fragments.includes(n));if(i!==undefined){const pos=world.fragments[i].root.position;return {x:pos.x,z:pos.z,node:14+i,name:'LJUSFRAGMENT '+(i+1)}}}return {...current(),name:current().short}}
function stopGuide(){guide=[];guideIndex=0;$('guideButton').classList.remove('active');$('guideButton').textContent='↗ FÖLJ SPÅRET'}
function route(start,end){let dist=nodes.map(()=>Infinity),prev=nodes.map(()=>-1),q=new Set(nodes.map((_,i)=>i));dist[start]=0;while(q.size){let u=[...q].reduce((a,b)=>dist[a]<dist[b]?a:b);q.delete(u);if(u===end||!isFinite(dist[u]))break;for(const edge of edges){let v=edge[0]===u?edge[1]:edge[1]===u?edge[0]:-1;if(v<0||!q.has(v))continue;let d=dist[u]+Math.hypot(nodes[u][0]-nodes[v][0],nodes[u][1]-nodes[v][1]);if(d<dist[v]){dist[v]=d;prev[v]=u}}}let path=[],u=end;while(u!==-1){path.unshift(nodes[u]);u=prev[u]}return path}
function startGuide(){if(mode!=='play')return;if(guide.length){stopGuide();return}const t=target();let nearest=0;for(let i=1;i<nodes.length;i++)if(Math.hypot(player.x-nodes[i][0],player.z-nodes[i][1])<Math.hypot(player.x-nodes[nearest][0],player.z-nodes[nearest][1]))nearest=i;guide=route(nearest,t.node).map(p=>({x:p[0],z:p[1]}));guide.push({x:t.x,z:t.z});guideIndex=0;$('guideButton').textContent='Ⅱ PAUSA GUIDNING';$('guideButton').classList.add('active');toast('Följ stadens spår','Du går automatiskt. Dra för att se dig omkring. Styr själv för att avbryta.',4)}
function refresh(){const m=current(),done=save.done===5;$('missionNumber').textContent=done?'05 / 05':String(active()+1).padStart(2,'0')+' / 05';$('missionKind').textContent=done?'STADENS SOLSIGILL':m.kind;$('missionTitle').textContent=done?'Karlstad är bara början.':m.title;$('missionHint').textContent=done?'Alla fem uppdrag klara. Fortsätt utforska eller se stadens aktuella tips.':scanning?`Scanna tre ljusfragment i trädgården. ${save.fragments.length} / 3 funna.`:m.hint;$('score').textContent=score()+' XP';$('progressDots').innerHTML=MISSIONS.map((_,i)=>`<i class="${i<save.done?'done':i===save.done?'current':''}"></i>`).join('');world.beacons.slice(0,5).forEach((b,i)=>b.root.setEnabled(!done&&i===active()&&!scanning));world.fragments.forEach((b,i)=>b.root.setEnabled(scanning&&!save.fragments.includes(i)));$('guideButton').hidden=done}
function startPlay(){introTime=24;$('fade').style.opacity=0;$('introTitles').style.opacity=0;world.hero.root.setEnabled(false);setMode('play');if(save.done>0){const p=nodes[current().node];player.x=p[0];player.z=p[1]+(current().id==='park'?7:-7)}yaw=0;pitch=0;world.camera.fov=1.22;refresh();toast('Välkommen till Karlstad','Gå fritt eller välj Följ spåret. Scanna när du är nära en signal.',7);if(save.done===5)finalPanel()}
function animateHero(t){const hero=world.hero;hero.root.position.set(0,0,-27+Math.max(0,t-11)*.68);hero.root.rotation.y=0;hero.legs.forEach((m,i)=>m.rotation.x=Math.sin(t*5+i*Math.PI)*.35);hero.arms.forEach((m,i)=>m.rotation.x=-Math.sin(t*5+i*Math.PI)*.28)}
const introKeys=[{t:0,p:[-109,48,-113],look:[5,8,53]},{t:6,p:[-75,27,-49],look:[-6,7,35]},{t:12,p:[-9,8,-36],look:[15,5,20]},{t:17,p:[-.8,3.2,-28],look:[0,1.5,-17]},{t:23,p:[0,1.74,-24],look:[4,2,8]}];
function cinematicCamera(keys,t){let i=0;while(i<keys.length-2&&t>keys[i+1].t)i++;let a=keys[i],b=keys[i+1],f=clamp((t-a.t)/(b.t-a.t),0,1),s=f*f*(3-2*f);const B=BABYLON;world.camera.position.set(...a.p.map((v,n)=>mix(v,b.p[n],s)));world.camera.setTarget(new B.Vector3(...a.look.map((v,n)=>mix(v,b.look[n],s))))}
function intro(dt){introTime+=dt;cinematicCamera(introKeys,introTime);animateHero(introTime);world.scanner.setEnabled(false);$('introTitles').style.opacity=introTime>16?'0':introTime<1?'0':'1';$('introTitles').style.transform=introTime>16?'translateY(12px)':'none';$('introCaption').textContent=introTime<7?'KLARÄLVEN · GYLLENE TIMMEN':introTime<14?'TINGVALLASTADEN · NYA SPÅR':'DITT ÄVENTYR BÖRJAR HÄR';if(introTime>=23)startPlay()}
function source(m){return `<div class="source">VERKLIG PLATS · <a href="${m.url}" target="_blank" rel="noopener noreferrer">${m.source} ↗</a><br>3D-miljön är en konstnärlig tolkning, inte en exakt byggnadsmodell.</div>`}
function panel(html,type='mission'){lastFocus=document.activeElement;stopGuide();setMode('paused');modalType=type;$('dialogContent').innerHTML=html;$('modal').hidden=false;$('closeModal').focus()}
function closePanel(){$('modal').hidden=true;modalType='';setMode('play');lastFocus?.focus?.();refresh()}
function missionPanel(){const m=current();audio.fx('click');if(save.done===5){finalPanel();return}if(m.id==='sandgrund'){panel(`<span class="eyebrow">KAPITEL 02 · SPÅR AV LJUS</span><div class="dialog-icon">✧</div><h2 id="dialogTitle">Konsten visar vägen.</h2><p>${m.story}</p><div class="fact">${m.fact}</div><button class="primary" data-action="startScan">AKTIVERA SCANNERN →</button>${source(m)}`);return}if(m.id==='bus'){panel(`<span class="eyebrow">KAPITEL 04 · RESA SMART</span><div class="dialog-icon">▰</div><h2 id="dialogTitle">Nästa: den gröna oasen.</h2><p>${m.story}</p><div class="fact">${m.fact}</div><button class="primary" data-action="ride">KLIV OMBORD I SPELET →</button><a class="secondary" href="${m.url}" target="_blank" rel="noopener noreferrer">RIKTIGA AVGÅNGAR ↗</a>${source(m)}`);return}panel(`<span class="eyebrow">UPPDRAG ${active()+1} · ${m.kind}</span><div class="dialog-icon">${m.icon}</div><h2 id="dialogTitle">${m.title}</h2><p>${m.story}</p><div class="fact">${m.fact}</div><p><strong>${m.question}</strong></p><div class="options">${m.options.map((s,i)=>`<button class="option" data-answer="${i}">${s}</button>`).join('')}</div><div id="answerFeedback" class="answer-feedback" role="status"></div>${source(m)}`)}
function completeMission(){if(save.done>=5)return;const m=current();save.done++;save.fragments=[];scanning=false;persist();refresh();audio.fx('win');panel(`<span class="eyebrow">UPPDRAG AVKLARAT · +${m.xp} XP</span><div class="dialog-icon">✳</div><h2 id="dialogTitle">En ny del av staden.</h2><p>${m.success}</p><div class="fact">${save.done} / 5 uppdrag · ${score()} XP</div><button class="primary" data-action="next">${save.done===5?'SE DITT SOLSIGILL':'FÖLJ NÄSTA SPÅR'} →</button>`,'complete')}
function finalPanel(){panel(`<span class="eyebrow">EFTER REGNET · PILOTEN AVKLARAD</span><div class="dialog-icon">✳</div><h2 id="dialogTitle">Stadens solsigill är ditt.</h2><p>Du hittade bibliotekets nya hem, följde kulturspåret och reste vidare till naturen. Fem platser. En berättelse som fortsätter.</p><div class="fact">${score()} XP · 5 / 5 UPPDRAG<br>Din resa sparas på den här enheten.</div><button class="primary" data-action="events">DET HÄNDER I KARLSTAD ↗</button><button class="secondary" data-action="resume">UTFORSKA VIDARE</button>`,'final')}
function eventsPanel(){let now=new Date(),currentEvent=now>=new Date(2026,4,30)&&now<new Date(2026,10,9);panel(`<span class="eyebrow">LEVANDE STAD · HIDDEN GEMS</span><div class="dialog-icon">✦</div><h2 id="dialogTitle">Nästa upptäckt är verklig.</h2><p>Utställningar, föreställningar och nya mötesplatser kan bli tidsbegränsade uppdrag i nästa version.</p>${currentEvent?'<div class="fact"><strong>SANDGRUND LARS LERIN</strong><br>Gästutställning med Sven X:et Erixson, 30 maj–8 november 2026.<br><a href="https://sandgrund.org/sandgrund/" target="_blank" rel="noopener noreferrer">Se aktuell information hos Sandgrund ↗</a></div>':''}<a class="primary" href="https://visitkarlstad.se/visit-karlstad/evenemang" target="_blank" rel="noopener noreferrer">STADENS EVENEMANG ↗</a><button class="secondary" data-action="resume">FORTSÄTT UTFORSKA</button><div class="source">Kontrollera datum, entré och öppettider hos arrangören. Inga sponsoravtal eller verkliga erbjudanden är kopplade till piloten.</div>`,'events')}
function pause(){if(!world||!['play','paused'].includes(mode))return;if(mode==='paused'&&!$('modal').hidden){closePanel();return}panel(`<span class="eyebrow">EN PAUS VID ÄLVEN</span><h2 id="dialogTitle">Staden väntar.</h2><p>WASD eller vänster styrspak: gå.<br>Dra över bilden eller använd muslås: se dig omkring.<br>Shift: spring · E / ⌖: scanna · M: karta.</p><p>GRAFIK</p><div class="settings-row">${[['mobile','MOBIL'],['balanced','BALANSERAD'],['high','FILMISK']].map(([id,s])=>`<button data-quality="${id}" class="${quality===id?'selected':''}">${s}</button>`).join('')}</div><button class="primary" data-action="resume">FORTSÄTT →</button><button class="secondary" data-action="events">AKTUELLA TIPS</button><button class="secondary" data-action="intro">SE INTROT IGEN</button><button class="secondary" data-action="resetAsk">BÖRJA OM</button><div class="source">Babylon.js · Originalgrafik och musik · Mobilen kan behöva lägre grafik.<br>Den här 3D-piloten är en konstnärlig, komprimerad tolkning av Karlstad.</div>`,'pause')}
function scan(){if(mode!=='play')return;scanRecoil=.12;$('scanFlash').style.opacity='.55';setTimeout(()=>$('scanFlash').style.opacity=0,240);audio.fx('scan');const t=target(),dist=Math.hypot(player.x-t.x,player.z-t.z);if(save.done===5){finalPanel();return}if(dist>7){toast('Signalen finns längre bort',`${Math.round(dist)} meter i spelvärlden. Följ markören eller välj Följ spåret.`,3);return}stopGuide();if(scanning){let index=[0,1,2].find(i=>!save.fragments.includes(i));save.fragments.push(index);persist();refresh();audio.fx('win');if(save.fragments.length===3){completeMission()}else{toast('Ljusfragment hittat',`${save.fragments.length} / 3 · Scanna nästa signal i trädgården.`,4)}}else missionPanel()}
function startRide(){$('modal').hidden=true;setMode('ride');rideTime=0;rideStart=time;$('rideCaption').hidden=false;$('fade').style.opacity='.95';setTimeout(()=>$('fade').style.opacity=0,450);audio.fx('bus')}
const busPath=[[-3,-16],[-3,-46],[-35,-48],[-78,-48],[-114,-48],[-124,-68]];
function ride(dt){rideTime+=dt;const duration=17,p=clamp(rideTime/duration,0,.9999)*(busPath.length-1),i=Math.floor(p),f=p-i,a=busPath[i],b=busPath[i+1],smooth=f*f*(3-2*f),x=mix(a[0],b[0],smooth),z=mix(a[1],b[1],smooth);world.bus.position.set(x,0,z);world.bus.rotation.y=Math.atan2(b[0]-a[0],b[1]-a[1]);const ang=world.bus.rotation.y;let cameraPos=new BABYLON.Vector3(x-Math.sin(ang)*10+7,5.2+Math.sin(rideTime*.18)*1.5,z-Math.cos(ang)*10-2);world.camera.position=BABYLON.Vector3.Lerp(world.camera.position,cameraPos,1-Math.exp(-dt*2));world.camera.setTarget(new BABYLON.Vector3(x,1.65,z));world.camera.fov=1.08;if(rideTime>duration){player.x=-124;player.z=-78;yaw=Math.PI;pitch=0;$('rideCaption').hidden=true;setMode('play');completeMission()}}
function move(dt){let t=target(),distance=Math.hypot(player.x-t.x,player.z-t.z),dx=0,dz=0,manual=false,sprint=keys.has('shift')||input.sprint;const fw=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0)+input.y,side=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+input.x;
 if(Math.abs(fw)+Math.abs(side)>.07){manual=true;if(guide.length)stopGuide();let len=Math.max(1,Math.hypot(fw,side));dx=(Math.sin(yaw)*fw+Math.cos(yaw)*side)/len;dz=(Math.cos(yaw)*fw-Math.sin(yaw)*side)/len}
 if(guide.length&&!manual){let n=guide[guideIndex],d=Math.hypot(n.x-player.x,n.z-player.z);if(d<1){guideIndex++;if(guideIndex>=guide.length){stopGuide();toast('Du är framme','Tryck på Undersök eller scannern för att fortsätta.',4)}}if(guide.length){n=guide[guideIndex];d=Math.hypot(n.x-player.x,n.z-player.z);dx=(n.x-player.x)/Math.max(d,.001);dz=(n.z-player.z)/Math.max(d,.001);if(time-lookTime>2)yaw+=deltaAngle(yaw,Math.atan2(dx,dz))*Math.min(1,dt*3);sprint=true;if(distance<5.0){stopGuide();dx=dz=0;toast('Signalen är nära','Scanna platsen för att öppna uppdraget.',3)}}}
 const speed=sprint?7.0:3.6,step=speed*dt,oldX=player.x,oldZ=player.z;if(!world.collides(player.x+dx*step,player.z))player.x+=dx*step;if(!world.collides(player.x,player.z+dz*step))player.z+=dz*step;const moving=Math.hypot(player.x-oldX,player.z-oldZ)>.001;
 if(guide.length&&!moving&&Math.abs(dx)+Math.abs(dz)>.01){slowTime+=dt;if(slowTime>1.2){stopGuide();toast('Välj en fri väg','Gå ut på gatan och aktivera guidningen igen.',4);slowTime=0}}else slowTime=0;
 if(jumping>0||jumpVelocity>0){jumpVelocity-=10*dt;jumping=Math.max(0,jumping+jumpVelocity*dt);if(jumping===0)jumpVelocity=0}if(moving)bob+=dt*(sprint?11:7.5);const amplitude=moving?(sprint?.045:.022):.007;world.camera.position.set(player.x,1.74+jumping+Math.sin(bob)*amplitude,player.z);world.camera.rotation.set(pitch,yaw,Math.sin(bob*.5)*amplitude*.17);world.camera.fov=mix(world.camera.fov,sprint&&moving?1.34:1.22,Math.min(1,dt*4));world.scanner.position.set(.30+Math.sin(bob*.5)*amplitude*.25,-.31+Math.cos(bob)*amplitude*.25-scanRecoil,.69-scanRecoil*.8);world.scanner.rotation.x=.1+scanRecoil*2;scanRecoil=Math.max(0,scanRecoil-dt*.4);audio.tick(mode,dt,moving,sprint);
 const near=distance<=7;$('interactButton').hidden=!near;$('interactText').textContent=save.done===5?'SE SOLSIGILLET':scanning?'SCANNA FRAGMENT':'UNDERSÖK PLATSEN';$('reticle').classList.toggle('ready',near);if(near&&!seen.has(t.name)){seen.add(t.name);audio.fx('click')}
}
function drawRadar(){const c=$('radarCanvas').getContext('2d'),w=360,h=260,scale=1.8,cx=180,cy=140;const project=(x,z)=>[cx+(x-player.x)*scale,cy-(z-player.z)*scale];c.clearRect(0,0,w,h);c.fillStyle='#112930';c.fillRect(0,0,w,h);c.strokeStyle='#284149';c.lineWidth=1;for(let i=0;i<w;i+=30){c.beginPath();c.moveTo(i,0);c.lineTo(i,h);c.stroke()}for(let i=0;i<h;i+=30){c.beginPath();c.moveTo(0,i);c.lineTo(w,i);c.stroke()}let river=project(-102,170);c.fillStyle='#244d57';c.fillRect(river[0],river[1],50*scale,350*scale);c.strokeStyle='#77939166';c.lineWidth=5;for(let [a,b]of edges){let pa=project(...nodes[a]),pb=project(...nodes[b]);c.beginPath();c.moveTo(...pa);c.lineTo(...pb);c.stroke()}c.fillStyle='#72908a5a';for(const b of world.buildings){let p=project(b.x-b.w/2,b.z+b.d/2);c.fillRect(p[0],p[1],b.w*scale,b.d*scale)}if(guide.length){c.strokeStyle='#e5c881';c.lineWidth=2;c.setLineDash([4,4]);c.beginPath();c.moveTo(cx,cy);for(let i=guideIndex;i<guide.length;i++)c.lineTo(...project(guide[i].x,guide[i].z));c.stroke();c.setLineDash([])}const t=target(),p=project(t.x,t.z);c.fillStyle='#f2d69b';c.beginPath();c.arc(clamp(p[0],12,w-12),clamp(p[1],12,h-12),5,0,7);c.fill();c.save();c.translate(cx,cy);c.rotate(yaw);c.fillStyle='#e3f0e7';c.beginPath();c.moveTo(0,-8);c.lineTo(6,6);c.lineTo(0,3);c.lineTo(-6,6);c.closePath();c.fill();c.restore();c.fillStyle='#abc0bd';c.font='12px monospace';c.fillText('N',w-22,23)}
function updateHud(){if(!world)return;const t=target(),d=Math.hypot(player.x-t.x,player.z-t.z);$('distance').textContent=Math.round(d)+' M';$('markerLabel').textContent=t.name;$('markerDistance').textContent=Math.round(d)+' m';let heading=((yaw*180/Math.PI)%360+360)%360;$('compassDegrees').textContent=String(Math.round(heading)).padStart(3,'0')+'°';$('compassLabel').textContent=['N','NÖ','Ö','SÖ','S','SV','V','NV'][Math.round(heading/45)%8];$('districtName').textContent=player.x<-102?'Mariebergsskogen':player.z>70?'Sandgrundsudden':player.x<-37?'Älvpromenaden':'Tingvallastaden';const B=BABYLON,p=B.Vector3.Project(new B.Vector3(t.x,2.7,t.z),B.Matrix.Identity(),world.scene.getTransformMatrix(),new B.Viewport(0,0,innerWidth,innerHeight));const marker=$('objectiveMarker');let inFront=(t.x-player.x)*Math.sin(yaw)+(t.z-player.z)*Math.cos(yaw)>0;marker.style.visibility=inFront&&p.z>0&&p.z<1?'visible':'hidden';marker.style.left=clamp(p.x,70,innerWidth-70)+'px';marker.style.top=clamp(p.y,150,innerHeight-180)+'px';if(save.done===5)marker.style.visibility='hidden';drawRadar();world.drawScanner(d,active(),time)}
function animate(){if(!world)return;const now=performance.now(),dt=Math.min(.2,(now-(last||now))/1000);last=now;if(document.hidden)return;time+=dt;world.update(time,dt,active());if(mode==='intro'){intro(dt);audio.tick(mode,dt)}else if(mode==='play'){let remaining=dt;while(remaining>0){const step=Math.min(remaining,1/60);move(step);remaining-=step}}else if(mode==='ride'){ride(dt);audio.tick(mode,dt)}world.scene.render();if(softwareRenderer)softwareRenderer.draw(time);hudClock+=dt;if(hudClock>.1){hudClock=0;updateHud()}if(time>toastUntil)$('toast').classList.remove('visible');if(mode==='play'&&time>28&&!qualityAuto){frameSamples++;if(frameSamples===180){const fps=engine.getFps();if(fps<26&&quality!=='mobile'){quality=quality==='high'?'balanced':'mobile';world.setQuality(quality);toast('Grafiken har anpassats','En lättare grafiknivå ger jämnare rörelse. Du kan ändra i pausmenyn.',4)}qualityAuto=true}}}
async function boot(){try{if(!window.BABYLON)throw Error('Spelmotorn kunde inte hämtas. Kontrollera anslutningen och försök igen.');const software=!BABYLON.Engine.isSupported();engine=software?new BABYLON.NullEngine({renderWidth:innerWidth,renderHeight:innerHeight,textureSize:512}):new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,powerPreference:'high-performance',adaptToDeviceRatio:false});world=await createKarlstadWorld(engine,canvas,quality,(percent,text)=>{$('loadProgress').style.width=percent+'%';$('loadText').textContent=text});if(software){softwareRenderer=new KarlstadSoftwareRenderer(canvas,world);document.querySelector('.build-note').textContent='KOMPATIBILITETSLÄGE · FÖRENKLAD GRAFIK';quality='mobile';qualityAuto=true} $('loading').hidden=true;scanning=save.done===1&&save.fragments.length>0;setMode('intro');refresh();world.scanner.setEnabled(false);engine.runRenderLoop(animate);if(matchMedia('(prefers-reduced-motion:reduce)').matches)startPlay();window.addEventListener('resize',()=>engine.resize());canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();engine.stopRenderLoop();$('errorMessage').textContent='Grafikminnet behöver återställas. Ladda om spelet. Dina avslutade uppdrag är sparade.';$('engineError').hidden=false});}catch(err){console.error(err);$('loading').hidden=true;$('errorMessage').textContent=err.message;$('engineError').hidden=false}}
function syncSound(){const on=audio.on;$('soundButton').innerHTML=(on?'♫':'♪')+' <span>'+(on?'LJUD PÅ':'LJUD AV')+'</span>';$('soundButton').setAttribute('aria-label',on?'Stäng av ljud':'Aktivera ljud')}
function ensureAudio(){if(!audio.ctx)audio.start();syncSound()}
// Pointer and touch input. Look control stays on the canvas; buttons cannot turn the camera.
let drag=null,stickId=null;
canvas.addEventListener('pointerdown',e=>{if(mode!=='play')return;ensureAudio();if(e.pointerType==='mouse'&&e.button===0){try{canvas.requestPointerLock?.()?.catch?.(()=>{})}catch{}}drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(mode!=='play')return;let dx=0,dy=0;if(document.pointerLockElement===canvas){dx=e.movementX;dy=e.movementY}else if(drag&&drag.id===e.pointerId){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY}else return;yaw+=dx*.0031;pitch=clamp(pitch+dy*.0028,-1.05,1.05);lookTime=time});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>drag=null);
const stick=$('joystick');stick.addEventListener('pointerdown',e=>{if(mode!=='play')return;e.preventDefault();stickId=e.pointerId;stick.setPointerCapture(e.pointerId);ensureAudio();stickMove(e)});function stickMove(e){if(e.pointerId!==stickId)return;const r=stick.getBoundingClientRect(),max=37,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(max,Math.hypot(dx,dy));input.x=dx/len;input.y=-dy/len;$('joystickKnob').style.transform=`translate(${input.x*max}px,${-input.y*max}px)`}stick.addEventListener('pointermove',stickMove);for(const t of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(t,()=>{stickId=null;input.x=input.y=0;$('joystickKnob').style.transform=''});
$('sprintButton').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.sprint=true});for(const t of ['pointerup','pointercancel','lostpointercapture'])$('sprintButton').addEventListener(t,()=>input.sprint=false);
$('scanButton').onclick=$('interactButton').onclick=()=>{ensureAudio();scan()};$('skipIntro').onclick=()=>{if(!world)return;ensureAudio();startPlay()};$('soundButton').onclick=()=>{audio.toggle();syncSound()};$('guideButton').onclick=()=>{ensureAudio();startGuide()};$('pauseButton').onclick=pause;$('closeModal').onclick=closePanel;
$('dialogContent').addEventListener('click',e=>{const answer=e.target.closest('[data-answer]');if(answer){let choice=+answer.dataset.answer,m=current();if(choice===m.answer){answer.classList.add('correct');$('answerFeedback').textContent='Rätt! Du har hittat nästa ledtråd.';$('dialogContent').querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);setTimeout(()=>{if(modalType==='mission')completeMission()},600)}else{answer.classList.add('wrong');$('answerFeedback').textContent='Inte riktigt. Läs ledtråden och försök igen.';audio.fx('miss')}return}const q=e.target.closest('[data-quality]');if(q){quality=q.dataset.quality;qualityAuto=true;world.setQuality(quality);$('dialogContent').querySelectorAll('[data-quality]').forEach(b=>b.classList.toggle('selected',b===q));return}const b=e.target.closest('[data-action]');if(!b)return;audio.fx('click');switch(b.dataset.action){case'resume':closePanel();break;case'next':if(save.done===5)finalPanel();else{closePanel();startGuide()}break;case'startScan':scanning=true;closePanel();refresh();toast('Scanner aktiverad','Tre fragment. Följ signalerna och scanna när du är nära.',5);startGuide();break;case'ride':startRide();break;case'events':eventsPanel();break;case'intro':$('modal').hidden=true;introTime=0;world.hero.root.setEnabled(true);world.camera.fov=1.15;setMode('intro');break;case'resetAsk':panel('<span class="eyebrow">ETT NYTT ÄVENTYR</span><h2 id="dialogTitle">Börja från biblioteket?</h2><p>Detta nollställer poängen och uppdragen på den här enheten.</p><button class="primary" data-action="reset">JA, BÖRJA OM</button><button class="secondary" data-action="resume">FORTSÄTT SPELA</button>','reset');break;case'reset':world.bus.position.set(-3,0,-16);world.bus.rotation.y=Math.PI;save={done:0,fragments:[]};persist();scanning=false;player.x=0;player.z=-24;yaw=0;pitch=0;seen.clear();closePanel();refresh();toast('Nytt äventyr','Bibliotekets signal väntar på dig.',4)}});
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;let k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','shift','e','m'].includes(k))e.preventDefault();if(mode==='play')keys.add(k);if(e.repeat)return;if(k==='e')scan();if(k===' '&&mode==='play'&&jumping===0)jumpVelocity=4;if(k==='escape'){if(!$('mapOverlay').hidden)closeMap();else if(mode==='play'||mode==='paused')pause()}if(k==='m'&&world){if($('mapOverlay').hidden)openMap();else closeMap()}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();input.x=input.y=0;input.sprint=false;drag=null});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();input.x=input.y=0;audio.suspend();if(mode==='play')pause()}else{last=performance.now();audio.resume()}});
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.append(s)})}
async function initRealMap(){if(sceneMap||mapLoading)return;mapLoading=true;const el=$('realMap');el.innerHTML='<div class="map-fallback">Laddar karta över de verkliga platserna…</div>';try{const key=window.KARLSTAD_CITY_CONFIG?.googleMapsKey?.trim();if(key){await loadScript('https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&v=weekly');el.replaceChildren();sceneMap=new google.maps.Map(el,{center:{lat:59.3779,lng:13.496},zoom:14,disableDefaultUI:true,zoomControl:true});MISSIONS.forEach((m,i)=>new google.maps.Marker({map:sceneMap,position:{lat:m.lat,lng:m.lng},label:String(i+1),title:m.title}));}else{if(!window.L)await loadScript('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');el.replaceChildren();sceneMap=L.map(el).setView([59.3779,13.496],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'}).addTo(sceneMap);MISSIONS.forEach((m,i)=>{let icon=L.divIcon({className:'city-map-pin',html:`<span style="display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#ecd09a;color:#193039;border:2px solid #fff;font:bold 12px sans-serif">${i+1}</span>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([m.lat,m.lng],{icon}).addTo(sceneMap).bindPopup(m.title)})}}catch{el.innerHTML='<div class="map-fallback"><div>Karttjänsten kunde inte laddas.<br><br><a href="https://www.google.com/maps/search/?api=1&query=Karlstad" target="_blank" rel="noopener noreferrer">Öppna Karlstad i Google Maps ↗</a></div></div>'}mapLoading=false}
function openMap(){if(!world||!['play','paused'].includes(mode))return;stopGuide();setMode('paused');$('mapOverlay').hidden=false;$('mapMissions').innerHTML=MISSIONS.map((m,i)=>`<section class="map-mission ${i===active()?'active':''}"><small>${String(i+1).padStart(2,'0')} · ${i<save.done?'AVKLARAT':i===save.done?'AKTIVT UPPDRAG':'LÅST'}</small><h3>${m.title}</h3><p>${m.place}</p>${i===save.done?'<button data-map-guide="true">FÖLJ SPÅRET I 3D →</button><br>':''}<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(m.place+', Karlstad')}" target="_blank" rel="noopener noreferrer">VISA VERKLIG PLATS ↗</a></section>`).join('');initRealMap();if(sceneMap?.invalidateSize)setTimeout(()=>sceneMap.invalidateSize(),50);$('closeMap').focus()}
function closeMap(){$('mapOverlay').hidden=true;setMode('play');refresh()}
$('mapButton').onclick=openMap;$('closeMap').onclick=closeMap;$('mapMissions').addEventListener('click',e=>{if(e.target.closest('[data-map-guide]')){closeMap();startGuide()}});
// Keep keyboard focus inside an open dialog or map overlay.
 document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;let layer=!$('mapOverlay').hidden?$('mapOverlay'):!$('modal').hidden?$('modal'):null;if(!layer)return;const buttons=[...layer.querySelectorAll('button:not(:disabled),a[href]')].filter(el=>el.getClientRects().length);if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
boot();
})();
