/* Karlstad City Quest: a small, self-contained location game pilot. */
const $ = id => document.getElementById(id);
const STORE = 'karlstad-city-quest-pilot-v1';
const STEPS = [
  {id:'library',title:'Biblioteket har flyttat',short:'Nya biblioteket',kind:'STADSSERVICE',icon:'▤',place:'Arkaden · Östra Torggatan 9',lat:59.37995,lng:13.504023,xp:125,
    description:'Hitta stadens tillfälliga bibliotek. En ny plats, samma berättelser — och en ledtråd som tar dig vidare.',
    story:'En bok har lämnats tillbaka till fel byggnad. Ledtråden säger att du ska leta där Stadsbiblioteket och Kontaktcenter numera delar entré.',
    fact:'Stadsbiblioteket och Kontaktcenter finns tillfälligt i Arkaden medan Bibliotekshuset renoveras.',
    question:'På vilken adress hittar du det tillfälliga biblioteket?',options:['Östra Torggatan 9','Västra Torggatan 31','Stora torget 1'],answer:0,
    success:'Du hittade rätt. På lånekortets baksida syns en sol och orden ”Sök konsten vid älven”.',
    source:'Karlstads kommun',url:'https://karlstad.se/nyheter/uppleva-och-gora/uppleva-och-gora/2026-09-02-stadsbiblioteket-och-kontaktcenter-har-oppnat-i-sina-tillfalliga-lokaler'},
  {id:'sandgrund',title:'Spår av ljus',short:'Sandgrund',kind:'KULTUR',icon:'✧',place:'Sandgrund Lars Lerin',lat:59.384639,lng:13.502961,xp:150,
    description:'Följ ledtråden norrut och samla tre solfragment i en snabb sekvens med perspektivet från första person.',
    story:'Du når Sandgrund. För att tyda nästa ledtråd behöver du samla tre ljusfragment på vägen längs älven.',
    fact:'Sandgrund Lars Lerin ligger vid Sandgrundsudden, nära Värmlands Museum.',
    success:'Tre fragment bildar ordet ”MUSEET”. Nästa del av stadens berättelse väntar alldeles i närheten.',
    source:'Sandgrund Lars Lerin',url:'https://sandgrund.org/'},
  {id:'museum',title:'Stadens berättelser',short:'Värmlands Museum',kind:'UPPTÄCK',icon:'◈',place:'Värmlands Museum · Sandgrundsudden',lat:59.38492,lng:13.50124,xp:125,
    description:'Hitta museet, lös ledtråden och lås upp en resa mot en grönare del av Karlstad.',
    story:'Ljusspåret slutar vid museet. Titta omkring: vad heter området där kulturplatserna ligger?',
    fact:'Värmlands Museum ligger på Sandgrundsudden. Aktuella utställningar hittar du på museets egen webbplats.',
    question:'Vilken udde ligger Värmlands Museum på?',options:['Sandgrundsudden','Hammarö','Lamberget'],answer:0,
    success:'Rätt! På kartans nästa sida finns en bussbiljett märkt ”mot Mariebergsskogen”.',
    source:'Värmlands Museum',url:'https://varmlandsmuseum.se/besok-oss/hitta-hit/'},
  {id:'bus',title:'Ta staden vidare',short:'Bussäventyr',kind:'RESA SMART',icon:'▰',place:'Stora torget → Mariebergsskogen',lat:59.380750,lng:13.503111,xp:140,
    description:'Gör en spelad bussresa från centrum mot en grön pärla. Kontrollera verkliga avgångar hos Värmlandstrafik.',
    story:'Torgklockan ger nästa ledtråd: en grön oas väntar söder om centrum. Planera resan och se vart spåret tar dig.',
    fact:'Bussresan i spelet är en simulering. Öppna Värmlandstrafik för aktuella avgångar, hållplatser och biljettinformation.',
    success:'Du har följt resans ledtråd. Sista uppdraget väntar i Mariebergsskogen.',
    source:'Värmlandstrafik',url:'https://www.varmlandstrafik.se/'},
  {id:'park',title:'Den gröna hemligheten',short:'Mariebergsskogen',kind:'HIDDEN GEM',icon:'✳',place:'Mariebergsskogen · naturum Värmland',lat:59.369119,lng:13.487801,xp:160,
    description:'Resan avslutas vid Mariebergsskogen. Hitta naturum Värmland och samla pilotens sista ledtråd.',
    story:'Du kliver av vid den gröna oasen. En sista fråga återstår innan du får Karlstads solsigill.',
    fact:'I Mariebergsskogen finns naturum Värmland, där du kan upptäcka värmländsk natur. Kontrollera öppettider före besök.',
    question:'Vad heter platsen om värmländsk natur i Mariebergsskogen?',options:['naturum Värmland','Stadshuset','Sandgrund Lars Lerin'],answer:0,
    success:'Du hittade den gröna pärlan! Karlstad har fler historier kvar att upptäcka.',
    source:'Mariebergsskogen',url:'https://www.mariebergsskogen.se/naturum-varmland/naturum-1/'},
];
const START = [59.3799,13.4995];
let progress = readProgress(), mapController, selectedIndex = 0, toastTimer, busTimer, busFrame, sprint = null;
let audioContext, musicTimer, soundOn = false, lastFocus;

function readProgress(){try{const data=JSON.parse(localStorage.getItem(STORE));if(!data||!Array.isArray(data.done))throw 0;const ids=STEPS.map(s=>s.id);let i=0;while(i<ids.length&&data.done[i]===ids[i])i++;return {done:ids.slice(0,i),bonus:Array.isArray(data.bonus)?data.bonus.filter(id=>ids.includes(id)):[]}}catch{return {done:[],bonus:[]}}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(progress))}catch{}}
const activeIndex=()=>Math.min(progress.done.length,STEPS.length-1);
const totalScore=()=>progress.done.reduce((n,id)=>n+STEPS.find(s=>s.id===id).xp,0)+progress.bonus.length*40;
const isDone=i=>i<progress.done.length;
const isLocked=i=>i>progress.done.length;

function markIcon(step,i){const status=isDone(i)?'done':isLocked(i)?'locked':'active';return `<div class="quest-pin ${status}" aria-label="${step.short}"><div class="pin-glow">${isDone(i)?'✓':step.icon}</div><span class="pin-label">${step.short}</span></div>`}
function installLeaflet(){if(!window.L)return null;const m=L.map('map',{zoomControl:false,scrollWheelZoom:true}).setView(START,14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'}).addTo(m);L.control.zoom({position:'topright'}).addTo(m);
  const route=L.polyline([[STEPS[3].lat,STEPS[3].lng],[59.3776,13.4971],[59.3739,13.4942],[STEPS[4].lat,STEPS[4].lng]],{color:'#f5bf68',weight:4,dashArray:'7,10',opacity:.92}).addTo(m);route.bringToBack();
  const markers=STEPS.map((s,i)=>L.marker([s.lat,s.lng],{icon:L.divIcon({html:markIcon(s,i),className:'quest-marker',iconSize:[56,82],iconAnchor:[28,28]})}).addTo(m).on('click',()=>openStep(i)));
  let busMarker;return {name:'OPENSTREETMAP · PILOT',focus(i){m.flyTo([STEPS[i].lat-(innerWidth<700?.0015:0),STEPS[i].lng],i===4?15:16,{duration:.8})},refresh(){markers.forEach((p,i)=>p.setIcon(L.divIcon({html:markIcon(STEPS[i],i),className:'quest-marker',iconSize:[56,82],iconAnchor:[28,28]})))},bus(p){const start=STEPS[3],end=STEPS[4],pos=[start.lat+(end.lat-start.lat)*p,start.lng+(end.lng-start.lng)*p];if(!busMarker)busMarker=L.marker(pos,{icon:L.divIcon({html:'<div style="background:#f5c573;border:3px solid #fff;color:#152d31;border-radius:12px;padding:8px;font-size:20px;box-shadow:0 0 22px #f9ce8c">▰</div>',iconSize:[42,42]})}).addTo(m);busMarker.setLatLng(pos);if(p>.99){m.removeLayer(busMarker);busMarker=null}},destroy(){m.remove()}}}
function installGoogle(){const G=window.google?.maps;if(!G)return installLeaflet();const m=new G.Map($('map'),{center:{lat:START[0],lng:START[1]},zoom:14,disableDefaultUI:true,zoomControl:true,styles:[{elementType:'geometry',stylers:[{color:'#d9e4d7'}]},{elementType:'labels.text.fill',stylers:[{color:'#375454'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#9bc3ca'}]},{featureType:'poi',stylers:[{visibility:'off'}]}]});const markers=STEPS.map((s,i)=>new G.Marker({position:{lat:s.lat,lng:s.lng},map:m,label:{text:String(i+1),color:'#183238'},title:s.short}));markers.forEach((marker,i)=>marker.addListener('click',()=>openStep(i)));new G.Polyline({path:[{lat:STEPS[3].lat,lng:STEPS[3].lng},{lat:STEPS[4].lat,lng:STEPS[4].lng}],geodesic:false,strokeColor:'#d08328',strokeWeight:5,map:m});let busMarker;return {name:'GOOGLE MAPS · PILOT',focus(i){m.panTo({lat:STEPS[i].lat,lng:STEPS[i].lng});m.setZoom(i===4?15:16)},refresh(){markers.forEach((marker,i)=>marker.setLabel({text:isDone(i)?'✓':String(i+1),color:isLocked(i)?'#82918d':'#163238'}))},bus(p){const a=STEPS[3],b=STEPS[4],pos={lat:a.lat+(b.lat-a.lat)*p,lng:a.lng+(b.lng-a.lng)*p};if(!busMarker)busMarker=new G.Marker({position:pos,map:m,label:'▰',title:'Spelad bussresa'});busMarker.setPosition(pos);if(p>.99){busMarker.setMap(null);busMarker=null}}}}
function installFallback(){const el=$('fallbackMap');el.hidden=false;const buttons=STEPS.map((s,i)=>{const b=document.createElement('button');b.style.cssText=`position:absolute;left:${44+(s.lng-13.496)*1300}%;top:${36-(s.lat-59.380)*2400}%;z-index:1;border:0;background:none;transform:rotate(10deg)`;b.innerHTML=markIcon(s,i);b.onclick=()=>openStep(i);el.append(b);return b});return {name:'KARTVY SAKNAS · SPELET FUNGERAR',focus(){},refresh(){buttons.forEach((b,i)=>b.innerHTML=markIcon(STEPS[i],i))},bus(){}}}
function initMap(){const key=window.KARLSTAD_CITY_CONFIG?.googleMapsKey?.trim();if(key){const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&v=weekly&callback=karlstadMapsReady`;script.onerror=()=>{if(!mapController){mapController=installLeaflet()||installFallback();render()}};window.karlstadMapsReady=()=>{if(!mapController){mapController=installGoogle();render()}};document.head.append(script);setTimeout(()=>{if(!mapController){mapController=installLeaflet()||installFallback();render()}},8000)}else{mapController=installLeaflet()||installFallback();render()}}

function render(){const i=activeIndex(),s=STEPS[i],finished=progress.done.length===STEPS.length;$('score').textContent=totalScore();$('questCount').textContent=finished?'KLAR':`${String(i+1).padStart(2,'0')} / 05`;$('questKicker').textContent=finished?'PILOTENS FEM UPPDRAG KLARA':`UPPDRAG ${String(i+1).padStart(2,'0')} · ${s.kind}`;$('questTitle').textContent=finished?'Du hittade Karlstad!':s.title;$('questDescription').textContent=finished?'Du har följt ledtrådarna från biblioteket till Mariebergsskogen. Stadens nästa berättelser väntar.':s.description;$('questIcon').textContent=finished?'✳':s.icon;$('questLocation').textContent=finished?'Karlstad · fortsätt upptäcka':s.place;$('playQuest').innerHTML=finished?'SE DITT RESULTAT <span>↗</span>':'SPELA UPPDRAGET <span>↗</span>';$('trailCount').textContent=`${progress.done.length}/5`;$('mapCredit').textContent=mapController?.name||'KARTA LADDAS';$('bottomHint').textContent=finished?'UPPDRAGSKEDJAN KLAR — UTFORSKA VIDARE':'TRYCK PÅ DEN LYSANDE MARKÖREN FÖR ATT UTFORSKA';$('trail').innerHTML=STEPS.map((step,index)=>`<li><button class="trail-item ${isDone(index)?'done':isLocked(index)?'locked':'active'}" data-step="${index}" ${isLocked(index)?'disabled':''}><span class="trail-number">${isDone(index)?'✓':String(index+1).padStart(2,'0')}</span><span><strong>${step.short}</strong><small>${isDone(index)?'Slutfört':isLocked(index)?'Låst · följ ledtråden':'Aktivt uppdrag'}</small></span></button></li>`).join('');mapController?.refresh()}
function showToast(message){const e=$('toast');e.textContent=message;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2800)}
function openDialog(html){lastFocus=document.activeElement;$('dialogBody').innerHTML=html;$('dialogLayer').hidden=false;$('closeDialog').focus()}
function closeDialog(){if(busTimer){clearTimeout(busTimer);busTimer=null}if(busFrame){cancelAnimationFrame(busFrame);busFrame=null}if(mapController)mapController.bus(1);$('dialogLayer').hidden=true;lastFocus?.focus?.()}
function factLink(s){return `<div class="dialog-source">FAKTAGRANSKAD KÄLLA · <a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.source} ↗</a></div>`}
function directions(s){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.place+', Karlstad')}`}
function openStep(i){selectedIndex=i;const s=STEPS[i];if(isLocked(i)){showToast('Följ den aktiva ledtråden först');return}if(isDone(i)){openDialog(`<div class="dialog-index">UPPDRAG ${String(i+1).padStart(2,'0')} · AVKLARAT</div><div class="dialog-done">✓</div><div class="dialog-center"><h2 id="dialogTitle">${s.title}</h2><p>${s.success}</p><div class="dialog-row"><button class="dialog-primary" data-action="next">FÖLJ NÄSTA LEDTRÅD →</button></div></div>${factLink(s)}`);return}
  const options=s.options?`<div class="dialog-options">${s.options.map((option,n)=>`<button class="dialog-option" data-answer="${n}">${option}</button>`).join('')}</div><div class="dialog-feedback" id="answerFeedback" role="status"></div>`:'';
  const action=s.id==='sandgrund'?'<button class="dialog-primary" data-action="sprint">STARTA SOLSPRINT →</button>':s.id==='bus'?'<button class="dialog-primary" data-action="bus">SPELA BUSSRESAN →</button>':'';
  openDialog(`<div class="dialog-index">UPPDRAG ${String(i+1).padStart(2,'0')} · ${s.kind}</div><div class="dialog-illustration"><span>${s.icon}</span></div><h2 id="dialogTitle">${s.title}</h2><p>${s.story}</p><div class="dialog-fact"><strong>VÄRT ATT VETA</strong><br>${s.fact}</div>${s.question?`<p><strong>${s.question}</strong></p>${options}`:''}<div class="dialog-row">${action}<a class="dialog-secondary" href="${directions(s)}" target="_blank" rel="noopener noreferrer">VISA PLATS ↗</a>${s.id==='bus'?'<a class="dialog-secondary" href="https://www.varmlandstrafik.se/" target="_blank" rel="noopener noreferrer">RIKTIGA AVGÅNGAR ↗</a>':''}</div>${s.id!=='bus'?'<button class="dialog-secondary" data-action="checkin" style="margin-top:9px">JAG ÄR PÅ PLATS · BONUS +40</button>':''}${factLink(s)}`)}
function completeStep(){const i=selectedIndex;if(i!==progress.done.length)return;const s=STEPS[i];progress.done.push(s.id);save();render();tone('win');showToast(`+${s.xp} poäng · ${s.short}`);$('dialogLayer').hidden=true;openDialog(`<div class="dialog-index">UPPDRAG ${String(i+1).padStart(2,'0')} · AVKLARAT</div><div class="dialog-done">✳</div><div class="dialog-center"><h2 id="dialogTitle">Ledtråd funnen!</h2><p>${s.success}</p><div class="dialog-row"><button class="dialog-primary" data-action="next">${progress.done.length===STEPS.length?'SE SLUTRESULTAT →':'FÖLJ NÄSTA LEDTRÅD →'}</button></div></div>`)}
function nextStep(){closeDialog();if(progress.done.length===STEPS.length){openFinal();return}selectedIndex=activeIndex();mapController?.focus(selectedIndex);showToast(`Nytt uppdrag: ${STEPS[selectedIndex].title}`)}
function openFinal(){openDialog(`<div class="dialog-index">KARLSTAD CITY QUEST · PILOT KLAR</div><div class="dialog-done">✳</div><div class="dialog-center"><h2 id="dialogTitle">Stadens solsigill är ditt</h2><p>Du hittade biblioteket, följde kulturspåret och reste vidare mot Mariebergsskogen.</p><p><strong>${totalScore()} poäng · ${progress.done.length}/5 uppdrag</strong></p><div class="dialog-row"><button class="dialog-primary" data-action="events">SE VAD SOM HÄNDER I STADEN ↗</button></div></div>`)}
function openEvents(){openDialog(`<div class="dialog-index">LEVANDE STAD · HIDDEN GEMS</div><div class="dialog-illustration"><span>✦</span></div><h2 id="dialogTitle">Vad händer i Karlstad?</h2><p>Nya utställningar, scenkonst och andra evenemang kan bli tidsbegränsade speluppdrag. Under piloten hittar du aktuella tips direkt hos arrangörerna.</p><div class="dialog-row"><a class="dialog-primary" style="text-decoration:none" href="https://visitkarlstad.se/visit-karlstad/evenemang" target="_blank" rel="noopener noreferrer">VISIT KARLSTADS EVENEMANG ↗</a><a class="dialog-secondary" href="https://karlstad.se/uppleva-och-gora/kultur/kultur-i-karlstad---kalender" target="_blank" rel="noopener noreferrer">KULTURKALENDER ↗</a></div><div class="dialog-source">Evenemangens tid, plats och biljetter kontrolleras hos respektive arrangör.</div>`)}
function checkIn(){const s=STEPS[selectedIndex],feedback=$('answerFeedback');if(progress.bonus.includes(s.id)){showToast('Platsbonusen är redan hämtad');return}if(!navigator.geolocation){showToast('Platsfunktion saknas i webbläsaren');return}showToast('Kontrollerar din plats …');navigator.geolocation.getCurrentPosition(({coords})=>{if(selectedIndex!==activeIndex())return;const metres=distance(coords.latitude,coords.longitude,s.lat,s.lng);if(metres<=130){progress.bonus.push(s.id);save();render();tone('win');showToast('Plats bekräftad · +40 poäng');if(feedback)feedback.textContent='Platsbonus hämtad! Fortsätt med uppdraget.'}else showToast(`Du är cirka ${Math.round(metres)} m från platsen. Spela gärna på distans.`)},()=>showToast('Plats kunde inte läsas. Du kan spela vidare ändå.'),{enableHighAccuracy:true,timeout:9000,maximumAge:60000})}
function distance(a,b,c,d){const r=Math.PI/180,h=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return 12742000*Math.asin(Math.sqrt(h))}
function startBus(){const s=STEPS[3],body=$('dialogBody');body.innerHTML=`<div class="dialog-index">KAPITEL 04 · SPELAD BUSSRESA</div><div class="dialog-illustration"><span>▰</span></div><h2 id="dialogTitle">Nästa hållplats: en grön pärla</h2><p>Följ den animerade resan över kartan. Detta är en spelhändelse, ingen tidtabell eller bekräftelse på en riktig bussresa.</p><div class="dialog-fact"><strong>RESAN PÅGÅR</strong><br><span id="busProgress">På väg ut från centrum …</span></div><div class="dialog-row"><a class="dialog-secondary" href="https://www.varmlandstrafik.se/" target="_blank" rel="noopener noreferrer">PLANERA EN VERKLIG RESA ↗</a></div>${factLink(s)}`;const start=performance.now();function frame(now){if($('dialogLayer').hidden)return;const p=Math.min(1,(now-start)/5200);mapController?.bus(p);const label=$('busProgress');if(label)label.textContent=p<.33?'På väg ut från centrum …':p<.7?'Följ den gröna ledtråden …':'Snart framme vid Mariebergsskogen …';if(p<1)busFrame=requestAnimationFrame(frame);else{busFrame=null;completeStep()}}busFrame=requestAnimationFrame(frame)}
function createAudio(){if(audioContext)return;try{audioContext=new (window.AudioContext||window.webkitAudioContext)()}catch{}}
function note(freq,duration=.16,volume=.045,type='sine',delay=0){if(!audioContext||!soundOn)return;const t=audioContext.currentTime+delay,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+duration+.02)}
function tone(kind){if(kind==='win'){[440,554,659,880].forEach((f,i)=>note(f,.38,.065,'triangle',i*.08))}else if(kind==='collect'){note(720,.14,.06,'sine');note(1080,.19,.04,'sine',.06)}else if(kind==='miss')note(170,.19,.04,'triangle');else note(400,.08,.02,'triangle')}
function toggleAudio(){soundOn=!soundOn;if(soundOn){createAudio();audioContext?.resume();let n=0;musicTimer=setInterval(()=>{if(!soundOn||document.hidden)return;const notes=[220,293.66,329.63,293.66,246.94,329.63,392,329.63];note(notes[n%8],.8,.015,'triangle');if(n%4===0)note(110,.35,.022,'sine');n++},370);tone('collect')}else{clearInterval(musicTimer)}$('sound').classList.toggle('on',soundOn);$('sound').textContent=soundOn?'♫':'♪';$('sound').setAttribute('aria-label',soundOn?'Stäng av ljud':'Slå på ljud');$('sound').title=soundOn?'Ljud på':'Ljud av'}

function startSprint(){closeDialog();const layer=$('sprintLayer');layer.hidden=false;sprint={lane:1,collected:0,elapsed:0,objects:[],spawn:0,last:performance.now(),frame:0};$('sprintCount').textContent='0 / 3 ✦';$('sprintInstructions').textContent='BYT SPÅR MED A / D, PILARNA ELLER KNAPPARNA';sprint.frame=requestAnimationFrame(sprintTick)}
function stopSprint(reopen=true){if(!sprint)return;cancelAnimationFrame(sprint.frame);sprint=null;$('sprintLayer').hidden=true;if(reopen)openStep(1)}
function moveLane(change){if(!sprint)return;sprint.lane=Math.max(0,Math.min(2,sprint.lane+change));tone('move')}
function sprintTick(now){if(!sprint)return;let dt=Math.min(.04,(now-sprint.last)/1000);sprint.last=now;sprint.elapsed+=dt;sprint.spawn+=dt;if(sprint.spawn>.9){sprint.spawn=0;const n=Math.round(sprint.elapsed/.9),lane=(n*2+Math.floor(n/3))%3;sprint.objects.push({lane,p:0,type:n%4===3?'block':'sun',hit:false})}for(const o of sprint.objects){o.p+=dt*.48;if(o.p>.92&&!o.hit){o.hit=true;if(o.lane===sprint.lane){if(o.type==='sun'){sprint.collected++;tone('collect');$('sprintCount').textContent=`${sprint.collected} / 3 ✦`;if(sprint.collected>=3){stopSprint(false);completeStep();return}}else{tone('miss');$('sprintInstructions').textContent='HINDER! BYT SPÅR I TID'}}}}sprint.objects=sprint.objects.filter(o=>o.p<1.1);drawSprint(now/1000);if(sprint.elapsed>=28){stopSprint(false);openStep(1);showToast('Försök igen — samla tre solfragment')}else sprint.frame=requestAnimationFrame(sprintTick)}
function drawSprint(t){const canvas=$('sprintCanvas'),dpr=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=w*dpr;canvas.height=h*dpr}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);const horizon=h*.37;const sky=c.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#183a4b');sky.addColorStop(1,'#e7a87b');c.fillStyle=sky;c.fillRect(0,0,w,horizon);c.fillStyle='#eea871';c.beginPath();c.arc(w*.61,horizon-30,Math.max(30,w*.045),0,Math.PI*2);c.fill();
  for(let side of [-1,1])for(let i=12;i>=0;i--){const p=i/13,x=w/2+side*(w*.08+p*w*.54),bw=w*(.025+p*.14),bh=h*(.06+p*.4)*(i%3===0?1.22:1);c.fillStyle=i%2?'#274c51':'#34565a';c.fillRect(x-(side<0?bw:0),horizon-bh,bw,bh);c.fillStyle='#f8d39166';for(let j=0;j<3;j++)c.fillRect(x-(side<0?bw-8:8),horizon-bh+12+j*25,Math.max(3,bw-18),2)}
  c.fillStyle='#162e36';c.beginPath();c.moveTo(w*.43,horizon);c.lineTo(w*.57,horizon);c.lineTo(w*1.12,h);c.lineTo(-w*.12,h);c.closePath();c.fill();c.strokeStyle='#f2c77b8c';c.lineWidth=2;for(let divider of [-1,1]){c.beginPath();c.moveTo(w/2+divider*w*.024,horizon);c.lineTo(w/2+divider*w*.28,h);c.stroke()}for(let j=0;j<12;j++){const p=(j/12+t*.47)%1,y=horizon+(h-horizon)*p*p;c.strokeStyle=`rgba(247,217,152,${.12+p*.6})`;c.lineWidth=2+p*3;c.beginPath();c.moveTo(w/2-w*.08-p*w*.56,y);c.lineTo(w/2+w*.08+p*w*.56,y);c.stroke()}
  for(const o of sprint.objects){const p=o.p,y=horizon+(h-horizon)*p*p,lane=o.lane-1,x=w/2+lane*(w*.048+p*w*.23),size=8+p*48;if(o.type==='sun'){c.shadowColor='#ffd581';c.shadowBlur=15+p*36;c.fillStyle='#ffd481';c.beginPath();for(let k=0;k<10;k++){const a=k*Math.PI/5,r=k%2?size*.58:size;c.lineTo(x+Math.sin(a)*r,y+Math.cos(a)*r)}c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#fff6dc';c.beginPath();c.arc(x,y,size*.23,0,Math.PI*2);c.fill()}else{c.fillStyle='#e4755c';c.fillRect(x-size*.7,y-size*.6,size*1.4,size*1.2);c.strokeStyle='#fff2a9';c.lineWidth=3;c.strokeRect(x-size*.7,y-size*.6,size*1.4,size*1.2)}}
  const laneX=w/2+(sprint.lane-1)*w*.28;c.strokeStyle='#ffffffd9';c.lineWidth=3;c.beginPath();c.moveTo(laneX-20,h*.86);c.lineTo(laneX-7,h*.86);c.moveTo(laneX+7,h*.86);c.lineTo(laneX+20,h*.86);c.moveTo(laneX,h*.86-20);c.lineTo(laneX,h*.86-7);c.moveTo(laneX,h*.86+7);c.lineTo(laneX,h*.86+20);c.stroke();c.fillStyle='#f4c777';c.font='700 12px sans-serif';c.textAlign='center';c.fillText('FÅNGA SOLFRAGMENTEN',laneX,h*.86+43)}

$('playQuest').addEventListener('click',()=>progress.done.length===STEPS.length?openFinal():openStep(activeIndex()));$('focusQuest').addEventListener('click',()=>mapController?.focus(activeIndex()));$('eventsChip').addEventListener('click',openEvents);$('sound').addEventListener('click',toggleAudio);$('closeDialog').addEventListener('click',closeDialog);$('dialogLayer').addEventListener('click',event=>{if(event.target.dataset.close)closeDialog()});$('trail').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){const i=Number(b.dataset.step);mapController?.focus(i);openStep(i)}});
$('dialogBody').addEventListener('click',e=>{const answer=e.target.closest('[data-answer]');if(answer){const chosen=Number(answer.dataset.answer),s=STEPS[selectedIndex];if(chosen===s.answer){answer.classList.add('correct');$('dialogBody').querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);$('answerFeedback').textContent='Rätt svar! En ny ledtråd låses upp.';setTimeout(()=>{if(!$('dialogLayer').hidden&&selectedIndex===progress.done.length)completeStep()},550)}else{answer.classList.add('wrong');$('answerFeedback').textContent='Inte riktigt. Prova en annan ledtråd.';tone('miss')}return}const b=e.target.closest('[data-action]');if(!b)return;switch(b.dataset.action){case'next':nextStep();break;case'bus':startBus();break;case'sprint':startSprint();break;case'checkin':checkIn();break;case'events':openEvents()}});
$('reset').addEventListener('click',()=>{if(!confirm('Börja om från biblioteket och nollställ pilotens poäng?'))return;progress={done:[],bonus:[]};save();selectedIndex=0;closeDialog();render();mapController?.focus(0);showToast('Nytt äventyr startat')});$('laneLeft').addEventListener('click',()=>moveLane(-1));$('laneRight').addEventListener('click',()=>moveLane(1));$('exitSprint').addEventListener('click',()=>stopSprint());document.addEventListener('keydown',e=>{if(sprint){if(['ArrowLeft','a','A'].includes(e.key)){e.preventDefault();moveLane(-1)}if(['ArrowRight','d','D'].includes(e.key)){e.preventDefault();moveLane(1)}if(e.key==='Escape')stopSprint();return}if(e.key==='Escape'&&!$('dialogLayer').hidden)closeDialog()});
initMap();
