// A small software renderer for devices without WebGL. It uses the same scene,
// camera, geometry, level rules and controls as the accelerated version.
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
export class CanvasSceneRenderer {
 constructor({canvas}){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});if(!this.ctx)throw Error('No canvas renderer available');this.capabilities={getMaxAnisotropy:()=>1};this.ratio=1;this.width=innerWidth;this.height=innerHeight;this.textures=new Map();this.matrix=new THREE.Matrix4();this.vp=new THREE.Matrix4();this.frustum=new THREE.Frustum();this.sphere=new THREE.Sphere();this.position=new THREE.Vector3();this.scale=new THREE.Vector3();this.capabilities.isSoftwareRenderer=true}
 setPixelRatio(){this.ratio=1}
 setSize(w,h){this.width=w;this.height=h;this.canvas.width=w;this.canvas.height=h;this.canvas.style.width=w+'px';this.canvas.style.height=h+'px'}
 texture(mat){const image=mat.map?.image;if(!image)return null;const key=mat.map.uuid+':'+mat.color?.getHex();if(this.textures.has(key))return this.textures.get(key);const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d');x.drawImage(image,0,0);if(mat.color){x.globalCompositeOperation='multiply';x.fillStyle='#'+mat.color.getHexString();x.fillRect(0,0,c.width,c.height);x.globalCompositeOperation='source-over'}const p=this.ctx.createPattern(c,'repeat');this.textures.set(key,p);return p}
 render(scene,camera){const ctx=this.ctx,w=this.width,h=this.height;ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.fillStyle='#'+(scene.background?.getHexString()||'1b242b');ctx.fillRect(0,0,w,h);scene.updateMatrixWorld();camera.updateMatrixWorld();this.vp.multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);this.frustum.setFromProjectionMatrix(this.vp);const records=[],f=h/(2*Math.tan(camera.fov*Math.PI/360)),near=-Math.max(camera.near,.12);const fog=scene.fog,fogColor=fog?.color||new THREE.Color(0x17202a);const project=v=>[w/2+v[0]*f/-v[2],h/2-v[1]*f/-v[2]];const fogAt=d=>fog?Math.min(.97,Math.max(0,(d-fog.near)/(fog.far-fog.near))):0;
 scene.traverseVisible(o=>{
  if(o.isMesh){const geo=o.geometry,mat=Array.isArray(o.material)?o.material[0]:o.material;if(!mat||mat.opacity===0)return;if(!geo.boundingSphere)geo.computeBoundingSphere();this.sphere.copy(geo.boundingSphere).applyMatrix4(o.matrixWorld);if(!this.frustum.intersectsSphere(this.sphere))return;const p=geo.attributes.position,uv=geo.attributes.uv,idx=geo.index?.array;this.matrix.multiplyMatrices(camera.matrixWorldInverse,o.matrixWorld);const e=this.matrix.elements,points=new Array(p.count);for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i);points[i]=[e[0]*x+e[4]*y+e[8]*z+e[12],e[1]*x+e[5]*y+e[9]*z+e[13],e[2]*x+e[6]*y+e[10]*z+e[14],uv?uv.getX(i):0,uv?1-uv.getY(i):0]}
   const count=idx?idx.length:p.count;for(let i=0;i<count;i+=3){const a=points[idx?idx[i]:i],b=points[idx?idx[i+1]:i+1],c=points[idx?idx[i+2]:i+2];if(a[2]>near&&b[2]>near&&c[2]>near)continue;const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2];let nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;const facing=nx*a[0]+ny*a[1]+nz*a[2];if(mat.side!==THREE.DoubleSide&&((mat.side===THREE.BackSide&&facing<0)||(mat.side!==THREE.BackSide&&facing>=0)))continue;const norm=Math.hypot(nx,ny,nz)||1;nx/=norm;ny/=norm;nz/=norm;const depth=-(a[2]+b[2]+c[2])/3;if(depth>camera.far)continue;let poly=[a,b,c];if(poly.some(p=>p[2]>near)){const clipped=[];for(let j=0;j<3;j++){const v=poly[j],prev=poly[(j+2)%3],inside=v[2]<=near,prevInside=prev[2]<=near;if(inside!==prevInside){const t=(near-prev[2])/(v[2]-prev[2]);clipped.push(prev.map((v,i)=>v+(poly[j][i]-v)*t))}if(inside)clipped.push(v)}poly=clipped}if(poly.length<3)continue;const lit=mat.isMeshBasicMaterial?1:Math.min(1.35,.42+Math.abs(nx*.2+ny*.65+nz*.65)*.34+.7/(1+depth*.055));for(let j=1;j<poly.length-1;j++){const q=[poly[0],poly[j],poly[j+1]],s=q.map(project);if(s.every(p=>p[0]<0)||s.every(p=>p[0]>w)||s.every(p=>p[1]<0)||s.every(p=>p[1]>h))continue;records.push({type:'tri',depth,s,q,mat,lit,fog:fogAt(depth)})}}
  }else if(o.isSprite){this.position.setFromMatrixPosition(o.matrixWorld).applyMatrix4(camera.matrixWorldInverse);const z=-this.position.z;if(z<.15||z>camera.far)return;o.getWorldScale(this.scale);const s=project([this.position.x,this.position.y,this.position.z]);records.push({type:'sprite',depth:z,x:s[0],y:s[1],w:this.scale.x*f/z,h:this.scale.y*f/z,mat:o.material,fog:fogAt(z)})
  }else if(o.isLine){const p=o.geometry.attributes.position;this.matrix.multiplyMatrices(camera.matrixWorldInverse,o.matrixWorld);const ps=[];for(let i=0;i<p.count;i++){this.position.fromBufferAttribute(p,i).applyMatrix4(this.matrix);if(this.position.z<near)ps.push(project([this.position.x,this.position.y,this.position.z]))}if(ps.length>1)records.push({type:'line',depth:0,ps,mat:o.material})}
 });
 records.sort((a,b)=>b.depth-a.depth);for(const r of records){if(r.type==='tri'){const [a,b,c]=r.s,mat=r.mat,pattern=mat.map?this.texture(mat):null;ctx.save();ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.lineTo(...c);ctx.closePath();ctx.globalAlpha=mat.opacity??1;if(pattern&&r.depth>1){ctx.clip();const im=mat.map.image,pts=r.q.map(p=>[p[3]*im.width,p[4]*im.height]);const [t0,t1,t2]=pts,du1=t1[0]-t0[0],dv1=t1[1]-t0[1],du2=t2[0]-t0[0],dv2=t2[1]-t0[1],det=du1*dv2-du2*dv1;if(Math.abs(det)>.00001){const ax=((b[0]-a[0])*dv2-(c[0]-a[0])*dv1)/det,bx=((b[1]-a[1])*dv2-(c[1]-a[1])*dv1)/det,ay=((c[0]-a[0])*du1-(b[0]-a[0])*du2)/det,by=((c[1]-a[1])*du1-(b[1]-a[1])*du2)/det;ctx.setTransform(ax,bx,ay,by,a[0]-ax*t0[0]-ay*t0[1],a[1]-bx*t0[0]-by*t0[1]);ctx.fillStyle=pattern;ctx.fillRect(Math.min(...pts.map(p=>p[0]))-2,Math.min(...pts.map(p=>p[1]))-2,Math.max(...pts.map(p=>p[0]))-Math.min(...pts.map(p=>p[0]))+4,Math.max(...pts.map(p=>p[1]))-Math.min(...pts.map(p=>p[1]))+4);ctx.setTransform(1,0,0,1,0,0);if(r.lit<1){ctx.fillStyle=`rgba(0,0,0,${1-r.lit})`;ctx.fillRect(0,0,w,h)}}else{ctx.fillStyle=mat.color?.getStyle()||'#aaa';ctx.fill()}}
 else{const hex=mat.color?.getHex()??0xffffff;const channel=shift=>Math.min(255,Math.round(((hex>>shift)&255)*r.lit));ctx.fillStyle=`rgb(${channel(16)},${channel(8)},${channel(0)})`;ctx.fill()}if(r.fog>.01){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=`rgba(${(fogColor.getHex()>>16)&255},${(fogColor.getHex()>>8)&255},${fogColor.getHex()&255},${r.fog})`;ctx.fill()}ctx.restore();}
 else if(r.type==='sprite'){if(!r.mat.map?.image)continue;ctx.save();ctx.globalAlpha=(r.mat.opacity??1)*(1-r.fog);if(r.mat.blending===THREE.AdditiveBlending)ctx.globalCompositeOperation='screen';ctx.drawImage(r.mat.map.image,r.x-r.w/2,r.y-r.h/2,r.w,r.h);ctx.restore()}
 else if(r.type==='line'){ctx.strokeStyle=r.mat.color.getStyle();ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...r.ps[0]);r.ps.slice(1).forEach(p=>ctx.lineTo(...p));ctx.stroke()}}
 }
}
